### ISSUE TITLE
Next.js - Using getServerSideProps breaks trpc SSR?

### ISSUE THREAD

**Issue by ananni13** [trpc/trpc#1361]
I noticed that trpc SSR doesn't work if a page uses getServerSideProps to load props.

Is this a bug or intended? I didn't find anything in the docs regarding this behaviour with SSR.

I was able to reproduce the problem using the [next-prisma-starter](https://github.com/trpc/trpc/tree/main/examples/next-prisma-starter) and simply modifying the IndexPage and 'post.all' query to use server side props as an input.

Repository to test the problem: https://github.com/ananni13/trpc-prisma-starter-ssr-bug

Run `yarn dx` -> go to http://localhost:3000:

<details>
<summary>server log</summary>

```
 << query #1 post.all {
  input: { hello: undefined },
  result: TRPCClientError: [
    {
      "code": "invalid_type",
      "expected": "string",
      "received": "undefined",
      "path": [
        "hello"
      ],
      "message": "Required"
    }
  ]
      at Function.from (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/client/dist/TRPCClientError-bfee2bf5.cjs.dev.js:59:16)
      at Object.transformRPCResponse (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/client/dist/httpRequest-7bfaf300.cjs.dev.js:35:44)
      at /home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/client/links/httpBatchLink/dist/trpc-client-links-httpBatchLink.cjs.dev.js:191:30
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    originalError: undefined,
    shape: {
      message: '[\n' +
        '  {\n' +
        '    "code": "invalid_type",\n' +
        '    "expected": "string",\n' +
        '    "received": "undefined",\n' +
        '    "path": [\n' +
        '      "hello"\n' +
        '    ],\n' +
        '    "message": "Required"\n' +
        '  }\n' +
        ']',
      code: -32600,
      data: [Object]
    },
    data: {
      code: 'BAD_REQUEST',
      httpStatus: 400,
      stack: 'TRPCError: [\n' +
        '  {\n' +
        '    "code": "invalid_type",\n' +
        '    "expected": "string",\n' +
        '    "received": "undefined",\n' +
        '    "path": [\n' +
        '      "hello"\n' +
        '    ],\n' +
        '    "message": "Required"\n' +
        '  }\n' +
        ']\n' +
        '    at Procedure.parseInput (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:114:13)\n' +
        '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
        '    at async /home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:131:21\n' +
        '    at async wrapCallSafe (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:47:18)\n' +
        '    at async Array.<anonymous> (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:146:21)\n' +
        '    at async Procedure.call (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:165:20)\n' +
        '    at async eval (webpack-internal:///./node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b7ff366e.cjs.dev.js:205:24)\n' +
        '    at async Promise.all (index 0)\n' +
        '    at async resolveHTTPResponse (webpack-internal:///./node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b7ff366e.cjs.dev.js:201:24)\n' +
        '    at async Object.nodeHTTPRequestHandler (webpack-internal:///./node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b7ff366e.cjs.dev.js:356:18)',
      path: 'post.all'
    },
    isDone: false
  },
  elapsedMs: 201,
  context: {}
}
TRPCClientError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "hello"
    ],
    "message": "Required"
  }
]
    at Function.from (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/client/dist/TRPCClientError-bfee2bf5.cjs.dev.js:59:16)
    at Object.transformRPCResponse (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/client/dist/httpRequest-7bfaf300.cjs.dev.js:35:44)
    at /home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/client/links/httpBatchLink/dist/trpc-client-links-httpBatchLink.cjs.dev.js:191:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalError: undefined,
  shape: {
    message: '[\n' +
      '  {\n' +
      '    "code": "invalid_type",\n' +
      '    "expected": "string",\n' +
      '    "received": "undefined",\n' +
      '    "path": [\n' +
      '      "hello"\n' +
      '    ],\n' +
      '    "message": "Required"\n' +
      '  }\n' +
      ']',
    code: -32600,
    data: {
      code: 'BAD_REQUEST',
      httpStatus: 400,
      stack: 'TRPCError: [\n' +
        '  {\n' +
        '    "code": "invalid_type",\n' +
        '    "expected": "string",\n' +
        '    "received": "undefined",\n' +
        '    "path": [\n' +
        '      "hello"\n' +
        '    ],\n' +
        '    "message": "Required"\n' +
        '  }\n' +
        ']\n' +
        '    at Procedure.parseInput (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:114:13)\n' +
        '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
        '    at async /home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:131:21\n' +
        '    at async wrapCallSafe (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:47:18)\n' +
        '    at async Array.<anonymous> (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:146:21)\n' +
        '    at async Procedure.call (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:165:20)\n' +
        '    at async eval (webpack-internal:///./node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b7ff366e.cjs.dev.js:205:24)\n' +
        '    at async Promise.all (index 0)\n' +
        '    at async resolveHTTPResponse (webpack-internal:///./node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b7ff366e.cjs.dev.js:201:24)\n' +
        '    at async Object.nodeHTTPRequestHandler (webpack-internal:///./node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b7ff366e.cjs.dev.js:356:18)',
      path: 'post.all'
    }
  },
  data: {
    code: 'BAD_REQUEST',
    httpStatus: 400,
    stack: 'TRPCError: [\n' +
      '  {\n' +
      '    "code": "invalid_type",\n' +
      '    "expected": "string",\n' +
      '    "received": "undefined",\n' +
      '    "path": [\n' +
      '      "hello"\n' +
      '    ],\n' +
      '    "message": "Required"\n' +
      '  }\n' +
      ']\n' +
      '    at Procedure.parseInput (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:114:13)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async /home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:131:21\n' +
      '    at async wrapCallSafe (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:47:18)\n' +
      '    at async Array.<anonymous> (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:146:21)\n' +
      '    at async Procedure.call (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:165:20)\n' +
      '    at async eval (webpack-internal:///./node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b7ff366e.cjs.dev.js:205:24)\n' +
      '    at async Promise.all (index 0)\n' +
      '    at async resolveHTTPResponse (webpack-internal:///./node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b7ff366e.cjs.dev.js:201:24)\n' +
      '    at async Object.nodeHTTPRequestHandler (webpack-internal:///./node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b7ff366e.cjs.dev.js:356:18)',
    path: 'post.all'
  },
  isDone: false
}
Input for post.all: Hello
prisma:query SELECT "public"."Post"."id", "public"."Post"."title" FROM "public"."Post" WHERE 1=1 OFFSET $1
```

</details>

<details>
<summary>console log (error from the server and re-fetching query from client)</summary>

![console log](https://user-images.githubusercontent.com/37385837/147835084-70c2ac51-509e-48de-a2a1-ec26b5170770.jpg)

</details>

<details>
<summary>page html source (see <strong>'Posts&lt;!-- --&gt;(loading)'</strong> and error data under <code>__NEXT_DATA__</code> script)</summary>

```html
<!DOCTYPE html>
<html>
  <head>
    <style data-next-hide-fouc="true">body{display:none}</style>
    <noscript data-next-hide-fouc="true">
      <style>body{display:block}</style>
    </noscript>
    <meta name="viewport" content="width=device-width"/>
    <meta charSet="utf-8"/>
    <title>Prisma Starter</title>
    <link rel="icon" href="/favicon.ico"/>
    <meta name="next-head-count" content="4"/>
    <noscript data-n-css=""></noscript>
    <script defer="" nomodule="" src="/_next/static/chunks/polyfills.js?ts=1640974242104"></script><script src="/_next/static/chunks/webpack.js?ts=1640974242104" defer=""></script><script src="/_next/static/chunks/main.js?ts=1640974242104" defer=""></script><script src="/_next/static/chunks/pages/_app.js?ts=1640974242104" defer=""></script><script src="/_next/static/chunks/pages/index.js?ts=1640974242104" defer=""></script><script src="/_next/static/development/_buildManifest.js?ts=1640974242104" defer=""></script><script src="/_next/static/development/_ssgManifest.js?ts=1640974242104" defer=""></script><script src="/_next/static/development/_middlewareManifest.js?ts=1640974242104" defer=""></script>
    <noscript id="__next_css__DO_NOT_USE__"></noscript>
  </head>
  <body>
    <div id="__next" data-reactroot="">
      <main>
        <h1>Welcome to your tRPC starter!</h1>
        <p>Check <a href="https://trpc.io/docs">the docs</a> whenever you get stuck, or ping <a href="https://twitter.com/alexdotjs">@alexdotjs</a> on Twitter.</p>
        <h2>
          Posts<!-- -->(loading)
        </h2>
        <hr/>
        <form><label for="title">Title:</label><br/><input type="text" id="title" name="title"/><br/><label for="text">Text:</label><br/><textarea id="text" name="text"></textarea><br/><input type="submit"/></form>
      </main>
    </div>
    <script src="/_next/static/chunks/react-refresh.js?ts=1640974242104"></script><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"trpcState":{"json":{"mutations":[],"queries":[{"state":{"data":null,"dataUpdateCount":0,"dataUpdatedAt":0,"error":{"message":"[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"hello\"\n    ],\n    \"message\": \"Required\"\n  }\n]","data":{"code":"BAD_REQUEST","httpStatus":400,"stack":"TRPCError: [\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"hello\"\n    ],\n    \"message\": \"Required\"\n  }\n]\n    at Procedure.parseInput (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:114:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:131:21\n    at async wrapCallSafe (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:47:18)\n    at async Array.\u003canonymous\u003e (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:146:21)\n    at async Procedure.call (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:165:20)\n    at async eval (webpack-internal:///./node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b7ff366e.cjs.dev.js:205:24)\n    at async Promise.all (index 0)\n    at async resolveHTTPResponse (webpack-internal:///./node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b7ff366e.cjs.dev.js:201:24)\n    at async Object.nodeHTTPRequestHandler (webpack-internal:///./node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b7ff366e.cjs.dev.js:356:18)","path":"post.all"},"shape":{"message":"[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"hello\"\n    ],\n    \"message\": \"Required\"\n  }\n]","code":-32600,"data":{"code":"BAD_REQUEST","httpStatus":400,"stack":"TRPCError: [\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"hello\"\n    ],\n    \"message\": \"Required\"\n  }\n]\n    at Procedure.parseInput (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:114:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:131:21\n    at async wrapCallSafe (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:47:18)\n    at async Array.\u003canonymous\u003e (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:146:21)\n    at async Procedure.call (/home/ananni/Projects/Github/trpc-prisma-starter/node_modules/@trpc/server/dist/trpc-server.cjs.dev.js:165:20)\n    at async eval (webpack-internal:///./node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b7ff366e.cjs.dev.js:205:24)\n    at async Promise.all (index 0)\n    at async resolveHTTPResponse (webpack-internal:///./node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b7ff366e.cjs.dev.js:201:24)\n    at async Object.nodeHTTPRequestHandler (webpack-internal:///./node_modules/@trpc/server/dist/nodeHTTPRequestHandler-b7ff366e.cjs.dev.js:356:18)","path":"post.all"}}},"errorUpdateCount":1,"errorUpdatedAt":1640974242112,"fetchFailureCount":1,"fetchMeta":null,"isFetching":false,"isInvalidated":false,"isPaused":false,"status":"error"},"queryKey":["post.all",{"hello":null}],"queryHash":"[\"post.all\",{}]"}]},"meta":{"values":{"queries.0.state.data":["undefined"],"queries.0.queryKey.1.hello":["undefined"]},"referentialEqualities":{"queries.0.state.error.data":["queries.0.state.error.shape.data"]}}},"hello":"Hello"},"__N_SSP":true},"page":"/","query":{},"buildId":"development","isFallback":false,"gssp":true,"appGip":true,"scriptLoader":[]}</script>
  </body>
</html>
```

</details>

**Comment by ananni13** [comment]
Looks like it’s the same problem reported here #596, should’ve done a better research :)

So this is more of a Next.js issue, that App’s `getInitialProps` doesn’t have access to the pages `getServerSideProps` data right?

**Comment by KATT** [comment]
Yeah, this is a duplicate of #596 and there's not much I can do about it. If you want to use `getServerSideProps` you have to hydrate your own queries same way as [SSG](https://trpc.io/docs/ssg)

**Comment by ananni13** [comment]
Thanks, for now I just disabled SSR entirely since the app I'm building doesn't really _need_ it and trpc is too awesome to give up 😄

We can close this one and keep the discussion inside #596.
