### ISSUE TITLE
Error when running on `node v18.1.0` and using SSR

### ISSUE THREAD

**Issue by n1ghtmare** [trpc/trpc#1895]
I tried checking if someone has already reported this, but I couldn't find anything, so here I am:

When I have `ssr: true`, I'm getting the following error on `node v18.1.0` (I switched to an older version and everything works just fine):

```
TRPCClientError: fetch failed
    at Function.from (/home/ddimitrov/Dev/some-project/node_modules/@trpc/client/dist/TRPCClientError-bfee2bf5.cjs.dev.js:69:14)
    at /home/ddimitrov/Dev/some-project/node_modules/@trpc/client/links/httpBatchLink/dist/trpc-client-links-httpBatchLink.cjs.dev.js:208:50 {
  originalError: TypeError: fetch failed
      at Object.processResponse (node:internal/deps/undici/undici:5575:34)
      at node:internal/deps/undici/undici:5901:42
      at node:internal/process/task_queues:140:7
      at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
      at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8) {
    cause: InvalidArgumentError: invalid connection header
        at processHeader (node:internal/deps/undici/undici:2050:15)
        at new Request (node:internal/deps/undici/undici:1933:13)
        at [dispatch] (node:internal/deps/undici/undici:2858:25)
        at Client.dispatch (node:internal/deps/undici/undici:399:33)
        at [dispatch] (node:internal/deps/undici/undici:618:32)
        at Pool.dispatch (node:internal/deps/undici/undici:399:33)
        at [dispatch] (node:internal/deps/undici/undici:4159:27)
        at Agent2.dispatch (node:internal/deps/undici/undici:399:33)
        at node:internal/deps/undici/undici:6276:83
        at new Promise (<anonymous>) {
      code: 'UND_ERR_INVALID_ARG'
    }
  },
  shape: undefined,
  data: undefined,
  isDone: false,
  [cause]: TypeError: fetch failed
      at Object.processResponse (node:internal/deps/undici/undici:5575:34)
      at node:internal/deps/undici/undici:5901:42
      at node:internal/process/task_queues:140:7
      at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
      at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8) {
    cause: InvalidArgumentError: invalid connection header
        at processHeader (node:internal/deps/undici/undici:2050:15)
        at new Request (node:internal/deps/undici/undici:1933:13)
        at [dispatch] (node:internal/deps/undici/undici:2858:25)
        at Client.dispatch (node:internal/deps/undici/undici:399:33)
        at [dispatch] (node:internal/deps/undici/undici:618:32)
        at Pool.dispatch (node:internal/deps/undici/undici:399:33)
        at [dispatch] (node:internal/deps/undici/undici:4159:27)
        at Agent2.dispatch (node:internal/deps/undici/undici:399:33)
        at node:internal/deps/undici/undici:6276:83
        at new Promise (<anonymous>) {
      code: 'UND_ERR_INVALID_ARG'
    }
  }
}
```

I believe this has to do with some changes in the `fetch` api (in node).

Let me know, if I can provide more data, or if there is anything I could do to help out on this.

**Comment by KATT** [comment]
I haven't bothered much with SSR and React 18 -- with React 18 we'll do massive changes to how SSR works because of RSC.

Are you using Next.js? Can you provide a full repo with this?

**Comment by n1ghtmare** [comment]
@KATT Yes, I'm using Next.js, I'll try to prepare a repo with this issue as soon as I get some free time.

**Comment by n1ghtmare** [comment]
@KATT Yeah, I downloaded it and ran it, and you're right, it does indeed work. Hmmm. Will try to create a project from scratch and see if I get the same issue.

**Comment by KATT** [comment]
Feel free to reopen if it's still an issue, closing for now
