### ISSUE TITLE
Node 18 utility for filter out blocklisted request headers 

### ISSUE THREAD

**Issue by 3x071c** [trpc/trpc#2084]
**Update:** culprit is this: https://github.com/trpc/trpc/pull/2085#issuecomment-1175630821

---

After integrating the [WebSocket example](https://github.com/trpc/trpc/tree/main/examples/next-prisma-starter-websockets) into my own project I had noticed that server-side/SSR batched `fetch` calls fail. This behavior can also be observed with the official example itself (I had to remove some conflicting/incompatible deps and bump the rest to their latest versions). To illustrate, here are the (server-side) logs when rendering a page which queries the `healthz` key:

```
<< query #1 healthz {
  input: undefined,
  result: TRPCClientError: fetch failed
      at Function.from (.../node_modules/@trpc/client/dist/TRPCClientError-bfee2bf5.cjs.dev.js:69:14)
      at .../node_modules/@trpc/client/links/httpBatchLink/dist/trpc-client-links-httpBatchLink.cjs.dev.js:208:50 {
    originalError: TypeError: fetch failed
        at Object.processResponse (node:internal/deps/undici/undici:5555:34)
        at node:internal/deps/undici/undici:5877:42
        at node:internal/process/task_queues:140:7
        at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
        at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8) {
      cause: [InvalidArgumentError]
    },
    shape: undefined,
    data: undefined,
    isDone: false,
    [cause]: TypeError: fetch failed
        at Object.processResponse (node:internal/deps/undici/undici:5555:34)
        at node:internal/deps/undici/undici:5877:42
        at node:internal/process/task_queues:140:7
        at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
        at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8) {
      cause: [InvalidArgumentError]
    }
  },
  elapsedMs: 12,
  context: {}
}
TRPCClientError: fetch failed
    at Function.from (.../node_modules/@trpc/client/dist/TRPCClientError-bfee2bf5.cjs.dev.js:69:14)
    at .../node_modules/@trpc/client/links/httpBatchLink/dist/trpc-client-links-httpBatchLink.cjs.dev.js:208:50 {
  originalError: TypeError: fetch failed
      at Object.processResponse (node:internal/deps/undici/undici:5555:34)
      at node:internal/deps/undici/undici:5877:42
      at node:internal/process/task_queues:140:7
      at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
      at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8) {
    cause: InvalidArgumentError: invalid connection header
        at processHeader (node:internal/deps/undici/undici:2082:15)
        at new Request (node:internal/deps/undici/undici:1965:13)
        at [dispatch] (node:internal/deps/undici/undici:2891:25)
        at Client.dispatch (node:internal/deps/undici/undici:408:33)
        at [dispatch] (node:internal/deps/undici/undici:627:32)
        at Pool.dispatch (node:internal/deps/undici/undici:408:33)
        at [dispatch] (node:internal/deps/undici/undici:4174:27)
        at Agent.dispatch (node:internal/deps/undici/undici:408:33)
        at node:internal/deps/undici/undici:6255:83
        at new Promise (<anonymous>) {
      code: 'UND_ERR_INVALID_ARG'
    }
  },
  shape: undefined,
  data: undefined,
  isDone: false,
  [cause]: TypeError: fetch failed
      at Object.processResponse (node:internal/deps/undici/undici:5555:34)
      at node:internal/deps/undici/undici:5877:42
      at node:internal/process/task_queues:140:7
      at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
      at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8) {
    cause: InvalidArgumentError: invalid connection header
        at processHeader (node:internal/deps/undici/undici:2082:15)
        at new Request (node:internal/deps/undici/undici:1965:13)
        at [dispatch] (node:internal/deps/undici/undici:2891:25)
        at Client.dispatch (node:internal/deps/undici/undici:408:33)
        at [dispatch] (node:internal/deps/undici/undici:627:32)
        at Pool.dispatch (node:internal/deps/undici/undici:408:33)
        at [dispatch] (node:internal/deps/undici/undici:4174:27)
        at Agent.dispatch (node:internal/deps/undici/undici:408:33)
        at node:internal/deps/undici/undici:6255:83
        at new Promise (<anonymous>) {
      code: 'UND_ERR_INVALID_ARG'
    }
  }
}
```

Judging from the error message, trpc is attempting to set the `connection` header via Node's built-in `fetch` (since v18, internally undici), which [is reserved](https://github.com/nodejs/undici/issues/1470) (`invalid connection header`). There are suggestions to [allow user-provided connection headers](https://github.com/nodejs/undici/issues/1307), but it looks like that change is going to take some time. I assume it is being set to `keep-alive` for `node-fetch` compatibility - in any case, it would be very forthcoming if a workaround could be implemented, as it looks like I'm not able to use trpc at the moment without downgrading node (yay).

**Comment by KATT** [comment]
As a workaround, you can ponyfill `node-fetch` into `createTRPCClient({ fetch: /* ponyfill here */ })`

**Comment by KATT** [comment]
I am not sure this is an actual issue, I tried to reproduce in #2085 but it works fine. **Please add a reproduction 🙏**, I've invited you as a collaborator so you can push straight onto that branch. 


You might be using subscriptions & WebSocket on the server. See here for proper setup, it's an easy one to miss.

- https://github.com/trpc/trpc/blob/4ebd040f7d396080bcd63b59a302cead7aa6cdb7/examples/next-prisma-starter-websockets/src/pages/_app.tsx#L32-L44
- https://github.com/trpc/trpc/blob/4ebd040f7d396080bcd63b59a302cead7aa6cdb7/examples/next-prisma-starter-websockets/src/pages/_app.tsx#L57-L66

**Comment by 3x071c** [comment]
@KATT Thanks for looking into this! I have checked my setup once more and can confirm that I have properly integrated the example 😄 Since I'm able to reproduce this with the `next-prisma-starter-websockets` example as well, I doubt I've done something wrong here (though I'd be happy to be wrong). The overall CI/testing pipeline of this repo seems pretty lackluster, I have just pushed some updates to the branch and hopefully it will now correctly reproduce the problem (still working on it). Besides simplifying the GitHub workflow files, I would also highly recommend adding an [editorconfig file](https://editorconfig.org) (looks like it's mostly UTF-8/LF/Spaces/2), using the prettier CLI to validate proper formatting in a workflow step, and updating all dependencies in the workflow files, examples and lerna packages to their latest versions. If you're interested, I have some configuration files ready to get that set up for you in an automated fashion using renovate.

**Comment by KATT** [comment]
@3x071c thanks for digging in this, it seems indeed be something to do with forwarding the headers.

Do you know somewhere with a good list of headers that are "reserved"? Unsure if we should do this automatically or if we should provide a utility function that strips out extra headers.

**Comment by KATT** [comment]
@jlalmes @sachinraja a penny for your thoughts on what we should do here?

The problem is that when we do the SSR-prepass and forward headers from the client to the server we can send some headers that node.js' native v18 `fetch` doesn't like.
