### ISSUE TITLE
Unexpected request method OPTIONS

### ISSUE THREAD

**Issue by anthonyshew** [trpc/trpc#2094]
Hey, tRPC folks.

Loved your work here enough to take tRPC to production.

We're having a pretty major issue with the following, though.

```
{
  path: undefined,
  ctx: undefined,
  type: 'unknown',
  input: undefined,
  shape: {
    message: 'Unexpected request method OPTIONS',
    code: -32005,
    data: { code: 'METHOD_NOT_SUPPORTED', httpStatus: 405 }
  },
  error: TRPCError: Unexpected request method OPTIONS
      at Object.resolveHTTPResponse (/app/apps/web/.next/server/chunks/7239.js:439:13)
      at Object.nodeHTTPRequestHandler (/app/apps/web/.next/server/chunks/7239.js:231:44)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/apps/web/.next/server/chunks/7239.js:77:5
      at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:185:9)
      at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:395:9)
      at async Object.fn (/app/node_modules/next/dist/server/base-server.js:496:37)
      at async Router.execute (/app/node_modules/next/dist/server/router.js:226:36)
      at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:606:29)
      at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:321:20) {
    originalError: undefined,
    code: 'METHOD_NOT_SUPPORTED',
    [cause]: undefined
  }
}
```

We followed most convention in the nextjs-prisma starter. [Our repo can be found here](https://github.com/kittrgg/kittr). The only thing that I can think of that we did that isn't in the docs is we had to change the `[trpc].ts` right for a `[[...trpc]].ts` route for the NextJS catch-all.

We actually can't reproduce this ourselves in all honesty and we're looking for answers. Was hoping we aren't the first to run into this. We're thinking this looks a lot like a preflight CORS request and this is somewhat confirmed by our logs.

Would appreciate any guidance if we've seen this coming from tRPC before.

**Comment by KATT** [comment]
Hey @anthonyshew, 

You don't seem to have set up CORS in https://github.com/kittrgg/kittr/blob/master/apps/web/src/pages/api/trpc/%5B%5B...trpc%5D%5D.api.ts, could be that?


Maybe tRPC should be sending a 200 on `OPTIONS`-requests? I'm honestly not sure what the right approach is here.
