### ISSUE TITLE
react-query v4 being installed despite peerdependency

### ISSUE THREAD

**Issue by juliusmarminge** [trpc/trpc#2248]
Got an issue over at create-t3-app that I traced back to react-query v4 and it being incompatible with trpc v9.

__Steps to reproduce__

Reproduction repo: https://github.com/juliusmarminge/trpc-rqv4

Bootstrap a basic trpc app:

```bash
# Using create-t3-app (quickest)
# It is hotfixed in latest 5.1.0
npx create-t3-app@5.0.0 # select only trpc when prompted for packages

# Or using next and scaffolding urself
npx create-next-app --ts
npm install @trpc/client @trpc/server @trpc/react @trpc/next zod react-query
# add example code for pages/api/trpc/[trpc].ts and pages/_app.tsx
```

The following dependencies will be installed:

<details>
<summary>package.json</summary>

```json
  "dependencies": {
    "@trpc/client": "^9.26.2",
    "@trpc/next": "^9.26.2",
    "@trpc/react": "^9.26.2",
    "@trpc/server": "^9.26.2",
    "next": "12.2.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-query": "^4.0.0",
    "zod": "^3.17.9"
  },
```

</details>

Then run the application and the following error will occur:

<details>
<summary>Error log</summary>

```
error - Error: Cannot find module '../../../node_modules/use-sync-external-store/shim/index.js'
Require stack:
- /Users/julius/Dev/npm/node_modules/react-query/build/cjs/packages/react-query/src/useSyncExternalStore.js
- /Users/julius/Dev/npm/node_modules/react-query/build/cjs/packages/react-query/src/useQueries.js
- /Users/julius/Dev/npm/node_modules/react-query/build/cjs/packages/react-query/src/index.js
- /Users/julius/Dev/npm/node_modules/@trpc/react/dist/trpc-react.cjs.dev.js
- /Users/julius/Dev/npm/node_modules/@trpc/react/dist/trpc-react.cjs.js
- /Users/julius/Dev/npm/.next/server/pages/_app.js
- /Users/julius/Dev/npm/node_modules/next/dist/server/require.js
- /Users/julius/Dev/npm/node_modules/next/dist/server/next-server.js
- /Users/julius/Dev/npm/node_modules/next/dist/server/next.js
- /Users/julius/Dev/npm/node_modules/next/dist/server/lib/start-server.js
- /Users/julius/Dev/npm/node_modules/next/dist/cli/next-dev.js
- /Users/julius/Dev/npm/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/Users/julius/Dev/npm/node_modules/next/dist/build/webpack/require-hook.js:182:28)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/julius/Dev/npm/node_modules/react-query/build/cjs/packages/react-query/src/useSyncExternalStore.js:15:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/julius/Dev/npm/node_modules/react-query/build/cjs/packages/react-query/src/useSyncExternalStore.js',
    '/Users/julius/Dev/npm/node_modules/react-query/build/cjs/packages/react-query/src/useQueries.js',
    '/Users/julius/Dev/npm/node_modules/react-query/build/cjs/packages/react-query/src/index.js',
    '/Users/julius/Dev/npm/node_modules/@trpc/react/dist/trpc-react.cjs.dev.js',
    '/Users/julius/Dev/npm/node_modules/@trpc/react/dist/trpc-react.cjs.js',
    '/Users/julius/Dev/npm/.next/server/pages/_app.js',
    '/Users/julius/Dev/npm/node_modules/next/dist/server/require.js',
    '/Users/julius/Dev/npm/node_modules/next/dist/server/next-server.js',
    '/Users/julius/Dev/npm/node_modules/next/dist/server/next.js',
    '/Users/julius/Dev/npm/node_modules/next/dist/server/lib/start-server.js',
    '/Users/julius/Dev/npm/node_modules/next/dist/cli/next-dev.js',
    '/Users/julius/Dev/npm/node_modules/next/dist/bin/next'
  ],
  page: '/'
}
```

</details>

__Quick Fix:__

Go into the package.json and edit the react-query version to v3:

`"react-query": "^3.39.2",`

and run `npm install`. After which the application runs without errors.

**Comment by sachinraja** [comment]
We specify `react-query@^3.37.0`. If a different version is being installed, that's up to the package manager and there's nothing we can really do.

**Comment by KATT** [comment]
> We should update the docs to install `react-query@3`

Seems like a good idea, esp if they're going to tag (or have already tagged) it as `latest`

**Comment by KATT** [comment]
Feel free to open a new issue if you think this is a problem
