### ISSUE TITLE
bug: `yarn ts-node` fail

### ISSUE THREAD

**Issue by cawa-93** [trpc/trpc#2441]
### Provide environment information

```
  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 1.31 GB / 15.42 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.47)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    react: ^18.1.0 => 18.1.0
```

### Describe the bug

Initial `yarn install` failed in my environment. I use Git bash in Windows 10
```
$ yarn
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ preconstruct dev && yarn codegen
🎁 info project is valid!
🎁 success created links!
yarn run v1.22.10
$ yarn ts-node scripts/generateBigFRouter.ts
$ ts-node --compiler-options '{"module":"commonjs"}' scripts/generateBigFRouter.ts
undefined:1
'{module:commonjs}'
^

SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at parse (C:\Users\kozac\Dev\temp-projects\trpc\node_modules\ts-node\dist\util.js:52:45)
    at arg (C:\Users\kozac\Dev\temp-projects\trpc\node_modules\arg\index.js:122:24)
    at parseArgv (C:\Users\kozac\Dev\temp-projects\trpc\node_modules\ts-node\dist\bin.js:64:12)
    at main (C:\Users\kozac\Dev\temp-projects\trpc\node_modules\ts-node\dist\bin.js:25:18)
    at Object.<anonymous> (C:\Users\kozac\Dev\temp-projects\trpc\node_modules\ts-node\dist\bin.js:526:5)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### To reproduce

I do not know. I just cloned the project and tried to install the dependencies

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by sachinraja** [comment]
This is fixed on `next` (where most development is happening)
