### ISSUE TITLE
[v10] JSON parsing error when making zero-argument mutation

### ISSUE THREAD

**Issue by spiffytech** [trpc/trpc#2540]
### Provide environment information

```
  System:
    OS: Linux 5.19 openSUSE Tumbleweed 20220822
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 28.22 GB / 38.83 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.1.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.8.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 104.1.42.97
    Chrome: 104.0.5112.101
    Chromium: 104.0.5112.101
    Firefox: 103.0.2
  npmPackages:
    @trpc/client: ^10.0.0-alpha.52 => 10.0.0-alpha.52 
    @trpc/server: ^10.0.0-alpha.52 => 10.0.0-alpha.52
```

### Describe the bug

When I call a mutation that takes zero parameters the TRPC request fails with a JSON parsing error. If I change it to a query it works fine.

This is the error:

```
{
  "error": {
    "message": "Unexpected end of JSON input",
    "code": -32700,
    "data": {
      "code": "PARSE_ERROR",
      "httpStatus": 400,
      "stack": "TRPCError: Unexpected end of JSON input\n    at getRawProcedureInputOrThrow (file:///home/spiffytech/Documents/bootspoon/impermalink/node_modules/@trpc/server/dist/resolveHTTPResponse-83703ee8.mjs:80:15)\n    at resolveHTTPResponse (file:///home/spiffytech/Documents/bootspoon/impermalink/node_modules/@trpc/server/dist/resolveHTTPResponse-83703ee8.mjs:140:26)\n    at fastifyRequestHandler (file:///home/spiffytech/Documents/bootspoon/impermalink/node_modules/@trpc/server/dist/adapters/fastify/index.mjs:20:26)\n    at Object.<anonymous> (file:///home/spiffytech/Documents/bootspoon/impermalink/node_modules/@trpc/server/dist/adapters/fastify/index.mjs:62:15)\n    at Object.routeOptions.handler (/home/spiffytech/Documents/bootspoon/impermalink/node_modules/@fastify/websocket/index.js:139:24)\n    at preHandlerCallback (/home/spiffytech/Documents/bootspoon/impermalink/node_modules/fastify/lib/handleRequest.js:126:28)\n    at next (/home/spiffytech/Documents/bootspoon/impermalink/node_modules/fastify/lib/hooks.js:168:7)\n    at handleResolve (/home/spiffytech/Documents/bootspoon/impermalink/node_modules/fastify/lib/hooks.js:185:5)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
    }
  }
}
```

### To reproduce

```ts
// Server
const trpcRouter = trpc.router({
  logout: trpc.procedure.mutation(async ({ ctx }) => {
    await ctx.logout();
  })
});

// Client
await trpc.logout.mutate();
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Unable to reproduce, see #2548.

Are you sure you have set up data transformers on both client and server?

**Comment by KATT** [comment]
Added a test for it in #2548. If you still experience issues with the latest alpha, feel free to re-open.

**Comment by spiffytech** [comment]
I can no longer reproduce after upgrading to `10.0.0-proxy-alpha.57`.
