### ISSUE TITLE
feat: Koa support

### ISSUE THREAD

**Issue by jchnxu** [trpc/trpc#3094]
### Describe the feature you'd like to request

Do we have a plan to support koa?

### Describe the solution you'd like to see

@trpc/server/adapters/koa

### Desribe alternate solutions

I tried using c2k

```
  const router = new Router();
  router.use(
    '/trpc',
    c2k(trpcExpress.createExpressMiddleware({
      router: appRouter,
      createContext,
    })),
  );
  app.use(router.routes());
```

but there are errors
```
-> query hello client
/hacking/trpc/examples/express-server/node_modules/@trpc/client/dist/transformResult-e15ccdf6.js:15
        return new TRPCClientError(cause.message, {
               ^

TRPCClientError: invalid json response body at http://localhost:2021/trpc/hello,hello?batch=1&input=%7B%221%22%3A%22client%22%7D reason: Unexpected token N in JSON at position 0
    at Function.from (/hacking/trpc/examples/express-server/node_modules/@trpc/client/dist/transformResult-e15ccdf6.js:15:16)
    at null.<anonymous> (/hacking/trpc/examples/express-server/node_modules/@trpc/client/dist/links/httpBatchLink.js:204:80)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  meta: undefined,
  shape: undefined,
  data: undefined,
  [cause]: /hacking/trpc/examples/express-server/node_modules/node-fetch/lib/index.js:273
  				return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
  				                           ^

  FetchError: invalid json response body at http://localhost:2021/trpc/hello,hello?batch=1&input=%7B%221%22%3A%22client%22%7D reason: Unexpected token N in JSON at position 0
      at null.<anonymous> (/hacking/trpc/examples/express-server/node_modules/node-fetch/lib/index.js:273:32)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    type: 'invalid-json'
  }
}
```

### 👨‍👧‍👦 Contributing

- [x] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by jchnxu** [comment]
I made it work. Need more input on how we design the interface

```
const createTrpcKoaMiddleware = () => {
  // console.log("creating!!");
  return (async (ctx, next) => {
    // console.log("in createKoaMiddleware");
    const { req, res } = ctx;

    if (req.url?.startsWith(TRPC_PATH)) {
      // console.log(req.url);
      const path = (req.url || "").split("?")[0];
      const endpoint = path.slice((TRPC_PATH + "/").length);
      // console.log("endpoint", endpoint);

      // https://dustinpfister.github.io/2019/04/29/express-status/
      // the default of express is 200
      res.statusCode = 200;

      await nodeHTTPRequestHandler({
        router: appRouter,
        createContext: () => ({
          koaCtx: ctx,
        }),
        req,
        res,
        path: endpoint,
      });
    } else {
      await next();
    }
  }) as Application.Middleware;
};

```

**Comment by BlairCurrey** [comment]
I asked about a koa adapter and was told they didnt want to add anymore adapters to the repo ATM. https://discord.com/channels/867764511159091230/1023597568153895103/1023597568153895103

I do think Koa would be useful and would fit nicely in the trpc repo, but after hearing that I started https://github.com/BlairCurrey/trpc-koa-adapter Might be a useful cross-reference at the least.

**Comment by KATT** [comment]
Awesome!

Yeah, we're already up to our neck with supporting the whole API surface of tRPC and the adapters that we already have, so we can't really add more stuff into core right now. 

Please add your lib on https://trpc.io/docs/awesome-trpc though!

**Comment by jchnxu** [comment]
Thanks. Then in this case I guess it's worth moving all the adapters out of the main repo?  For example I use Koa and I don't need any else adapter.
