### ISSUE TITLE
Error thrown in Resolver always results in a 500 Status code

### ISSUE THREAD

**Issue by mgranderath** [trpc/trpc#331]
I have this resolver setup 

```typescript
export const authRouter = createRouter().mutation("login", {
  input: LoginInput,
  async resolve({ input, ctx }) {
    throw trpc.httpError.unauthorized("Optional message");
  },
});
````

Which should result in a 401 status code, however, the error that is actually sent by the endpoint is (with a 500 code):
```
TRPCError: Optional message
    at internalServerError (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\.next\server\pages\api\v2\trpc\[trpc].js:264:10)
    at getErrorFromUnknown (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\.next\server\pages\api\v2\trpc\[trpc].js:289:10)
    at Object.requestHandler (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\.next\server\pages\api\v2\trpc\[trpc].js:558:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async C:\Users\malte\Github\streamparty\monorepo\packages\website-next\.next\server\pages\api\v2\trpc\[trpc].js:184:5
    at async apiResolver (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\node_modules\next\dist\next-server\server\api-utils.js:8:1)
    at async DevServer.handleApiRequest (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\node_modules\next\dist\next-server\server\next-server.js:67:462)
    at async Object.fn (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\node_modules\next\dist\next-server\server\next-server.js:59:492)
    at async Router.execute (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\node_modules\next\dist\next-server\server\router.js:25:67)
    at async DevServer.run (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\node_modules\next\dist\next-server\server\next-server.js:69:1042)
    at async DevServer.handleRequest (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\node_modules\next\dist\next-server\server\next-server.js:34:504) {
  originalError: HTTPError: Optional message
      at Object.unauthorized (C:\Users\malte\Github\streamparty\monorepo\node_modules\@trpc\server\dist\http-c0b986e9.cjs.dev.js:98:28)
      at ProcedureWithInput.resolve [as resolver] (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\.next\server\pages\api\v2\trpc\[trpc].js:1381:66)
      at ProcedureWithInput.call (C:\Users\malte\Github\streamparty\monorepo\node_modules\@trpc\server\dist\router-91b6d32c.cjs.dev.js:61:31)
      at Router.invoke (C:\Users\malte\Github\streamparty\monorepo\node_modules\@trpc\server\dist\router-91b6d32c.cjs.dev.js:266:22)
      at Object.mutation (C:\Users\malte\Github\streamparty\monorepo\node_modules\@trpc\server\dist\router-91b6d32c.cjs.dev.js:285:21)
      at Object.requestHandler (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\.next\server\pages\api\v2\trpc\[trpc].js:460:29)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at async C:\Users\malte\Github\streamparty\monorepo\packages\website-next\.next\server\pages\api\v2\trpc\[trpc].js:184:5
      at async apiResolver (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\node_modules\next\dist\next-server\server\api-utils.js:8:1)
      at async DevServer.handleApiRequest (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\node_modules\next\dist\next-server\server\next-server.js:67:462)
      at async Object.fn (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\node_modules\next\dist\next-server\server\next-server.js:59:492)
      at async Router.execute (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\node_modules\next\dist\next-server\server\router.js:25:67)
      at async DevServer.run (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\node_modules\next\dist\next-server\server\next-server.js:69:1042)
      at async DevServer.handleRequest (C:\Users\malte\Github\streamparty\monorepo\packages\website-next\node_modules\next\dist\next-server\server\next-server.js:34:504) {
    originalError: undefined,
    code: 'UNAUTHENTICATED',
    statusCode: 401
  },
  code: 'INTERNAL_SERVER_ERROR'
}
````

Should this be the case? Let me know if you need any extra information

**Comment by KATT** [comment]
Will test!

**Comment by KATT** [comment]
Are you using Next.js or another http adapter?

**Comment by KATT** [comment]
This is strange - I have a test for this right here https://github.com/trpc/trpc/blob/ad3dc963cc37b26ec19078519321358ccf05707a/packages/server/test/errors.test.ts#L126

Checking if this is actually the case in a real app.

**Comment by mgranderath** [comment]
> Are you using Next.js or another http adapter?

I'm using the Next.js adapter

**Comment by KATT** [comment]
@all-contributors add @mgranderath for bug reporting

**Comment by KATT** [comment]
fix published at `6.1.1`

tip for upgrading: `npx ncu --filter /@trpc/ -u  && yarn`

**Comment by KATT** [comment]
Thanks for reporting - I'm not super happy with my fix - not sure why `instanceof` didn't work (works locally in tests but not in published version 🤔 ) but it's solved for now!

**Comment by mgranderath** [comment]
Thank you for the quick fix and the amazing project 💯
