### ISSUE TITLE
bug: ramda in trpc is undefined

### ISSUE THREAD

**Issue by ekil1100** [trpc/trpc#3563]
### Provide environment information

```
System:
  OS: macOS 13.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Memory: 447.50 MB / 32.00 GB
  Shell: 3.5.1 - /usr/local/bin/fish
Binaries:
  Node: 18.9.1 - ~/Library/pnpm/node
  Yarn: 1.22.11 - ~/Library/pnpm/yarn
  npm: 8.19.1 - ~/Library/pnpm/npm
  Watchman: 2023.01.02.00 - /usr/local/bin/watchman
Browsers:
  Brave Browser: 108.1.46.144
  Chrome: 108.0.5359.124
  Edge: 108.0.1462.76
  Firefox: 81.0.2
  Firefox Developer Edition: 78.0
  Safari: 16.2
npmPackages:
  @tanstack/react-query: ^4.3.8 => 4.20.9
  @trpc/client: ^10.8.1 => 10.8.1
  @trpc/next: ^10.8.1 => 10.8.1
  @trpc/react-query: ^10.8.1 => 10.8.1
  @trpc/server: ^10.8.1 => 10.8.1
  next: ^13.0.0 => 13.1.1
  react: ^18.2.0 => 18.2.0
  typescript: ^4.8.3 => 4.9.4
```

### Describe the bug

[Ramda](https://ramdajs.com/docs) is undefined in trpc routers. 

### Link to reproduction

https://stackblitz.com/edit/github-zdmtd7?file=src/pages/api/trpc/[trpc].ts

### To reproduce

I added a ramda function in query callback. 

Just do `npm i && npm run dev`.

### Additional information

The error is as following:

```
TRPCClientError: Cannot read properties of undefined (reading 'isEmpty')
    at TRPCClientError.from (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/client/dist/transformResult-6fb67924.mjs:4:20)
    at file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/client/dist/links/httpBatchLink.mjs:190:56
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  meta: {
    response: Response {
      [Symbol(realm)]: null,
      [Symbol(state)]: [Object],
      [Symbol(headers)]: [HeadersList]
    }
  },
  shape: {
    message: "Cannot read properties of undefined (reading 'isEmpty')",
    code: -32603,
    data: {
      code: 'INTERNAL_SERVER_ERROR',
      httpStatus: 500,
      stack: "TypeError: Cannot read properties of undefined (reading 'isEmpty')\n" +
        '    at eval (webpack-internal:///(api)/./src/pages/api/trpc/[trpc].ts:27:67)\n' +
        '    at resolveMiddleware (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:383:36)\n' +
        '    at callRecursive (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:419:38)\n' +
        '    at next (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:427:38)\n' +
        '    at inputMiddleware (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:263:16)\n' +
        '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
        '    at async callRecursive (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:419:32)\n' +
        '    at async resolve (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:447:24)\n' +
        '    at async file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/resolveHTTPResponse-b831e644.mjs:123:32\n' +
        '    at async Promise.all (index 0)\n' +
        '    at async resolveHTTPResponse (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/resolveHTTPResponse-b831e644.mjs:120:28)\n' +
        '    at async nodeHTTPRequestHandler (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/nodeHTTPRequestHandler-34404221.mjs:51:20)\n' +
        '    at async file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/adapters/next.mjs:39:9\n' +
        '    at async Object.apiResolver (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/api-utils/node.js:363:9)\n' +
        '    at async DevServer.runApi (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/next-server.js:487:9)\n' +
        '    at async Object.fn (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/next-server.js:749:37)\n' +
        '    at async Router.execute (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/router.js:253:36)\n' +
        '    at async DevServer.run (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/base-server.js:384:29)\n' +
        '    at async DevServer.run (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/dev/next-dev-server.js:741:20)\n' +
        '    at async DevServer.handleRequest (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/base-server.js:322:20)',
      path: 'greeting'
    }
  },
  data: {
    code: 'INTERNAL_SERVER_ERROR',
    httpStatus: 500,
    stack: "TypeError: Cannot read properties of undefined (reading 'isEmpty')\n" +
      '    at eval (webpack-internal:///(api)/./src/pages/api/trpc/[trpc].ts:27:67)\n' +
      '    at resolveMiddleware (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:383:36)\n' +
      '    at callRecursive (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:419:38)\n' +
      '    at next (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:427:38)\n' +
      '    at inputMiddleware (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:263:16)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async callRecursive (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:419:32)\n' +
      '    at async resolve (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:447:24)\n' +
      '    at async file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/resolveHTTPResponse-b831e644.mjs:123:32\n' +
      '    at async Promise.all (index 0)\n' +
      '    at async resolveHTTPResponse (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/resolveHTTPResponse-b831e644.mjs:120:28)\n' +
      '    at async nodeHTTPRequestHandler (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/nodeHTTPRequestHandler-34404221.mjs:51:20)\n' +
      '    at async file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/adapters/next.mjs:39:9\n' +
      '    at async Object.apiResolver (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/api-utils/node.js:363:9)\n' +
      '    at async DevServer.runApi (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/next-server.js:487:9)\n' +
      '    at async Object.fn (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/next-server.js:749:37)\n' +
      '    at async Router.execute (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/router.js:253:36)\n' +
      '    at async DevServer.run (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/base-server.js:384:29)\n' +
      '    at async DevServer.run (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/dev/next-dev-server.js:741:20)\n' +
      '    at async DevServer.handleRequest (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/base-server.js:322:20)',
    path: 'greeting'
  },
  [cause]: undefined
}
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 254 ms (247 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
TRPCClientError: Cannot read properties of undefined (reading 'isEmpty')
    at TRPCClientError.from (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/client/dist/transformResult-6fb67924.mjs:4:20)
    at file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/client/dist/links/httpBatchLink.mjs:190:56
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  meta: {
    response: Response {
      [Symbol(realm)]: null,
      [Symbol(state)]: [Object],
      [Symbol(headers)]: [HeadersList]
    }
  },
  shape: {
    message: "Cannot read properties of undefined (reading 'isEmpty')",
    code: -32603,
    data: {
      code: 'INTERNAL_SERVER_ERROR',
      httpStatus: 500,
      stack: "TypeError: Cannot read properties of undefined (reading 'isEmpty')\n" +
        '    at eval (webpack-internal:///(api)/./src/pages/api/trpc/[trpc].ts:27:67)\n' +
        '    at resolveMiddleware (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:383:36)\n' +
        '    at callRecursive (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:419:38)\n' +
        '    at next (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:427:38)\n' +
        '    at inputMiddleware (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:263:16)\n' +
        '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
        '    at async callRecursive (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:419:32)\n' +
        '    at async resolve (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:447:24)\n' +
        '    at async file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/resolveHTTPResponse-b831e644.mjs:123:32\n' +
        '    at async Promise.all (index 0)\n' +
        '    at async resolveHTTPResponse (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/resolveHTTPResponse-b831e644.mjs:120:28)\n' +
        '    at async nodeHTTPRequestHandler (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/nodeHTTPRequestHandler-34404221.mjs:51:20)\n' +
        '    at async file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/adapters/next.mjs:39:9\n' +
        '    at async Object.apiResolver (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/api-utils/node.js:363:9)\n' +
        '    at async DevServer.runApi (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/next-server.js:487:9)\n' +
        '    at async Object.fn (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/next-server.js:749:37)\n' +
        '    at async Router.execute (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/router.js:253:36)\n' +
        '    at async DevServer.run (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/base-server.js:384:29)\n' +
        '    at async DevServer.run (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/dev/next-dev-server.js:741:20)\n' +
        '    at async DevServer.handleRequest (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/base-server.js:322:20)',
      path: 'greeting'
    }
  },
  data: {
    code: 'INTERNAL_SERVER_ERROR',
    httpStatus: 500,
    stack: "TypeError: Cannot read properties of undefined (reading 'isEmpty')\n" +
      '    at eval (webpack-internal:///(api)/./src/pages/api/trpc/[trpc].ts:27:67)\n' +
      '    at resolveMiddleware (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:383:36)\n' +
      '    at callRecursive (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:419:38)\n' +
      '    at next (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:427:38)\n' +
      '    at inputMiddleware (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:263:16)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async callRecursive (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:419:32)\n' +
      '    at async resolve (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/index.mjs:447:24)\n' +
      '    at async file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/resolveHTTPResponse-b831e644.mjs:123:32\n' +
      '    at async Promise.all (index 0)\n' +
      '    at async resolveHTTPResponse (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/resolveHTTPResponse-b831e644.mjs:120:28)\n' +
      '    at async nodeHTTPRequestHandler (file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/nodeHTTPRequestHandler-34404221.mjs:51:20)\n' +
      '    at async file:///Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/@trpc/server/dist/adapters/next.mjs:39:9\n' +
      '    at async Object.apiResolver (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/api-utils/node.js:363:9)\n' +
      '    at async DevServer.runApi (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/next-server.js:487:9)\n' +
      '    at async Object.fn (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/next-server.js:749:37)\n' +
      '    at async Router.execute (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/router.js:253:36)\n' +
      '    at async DevServer.run (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/base-server.js:384:29)\n' +
      '    at async DevServer.run (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/dev/next-dev-server.js:741:20)\n' +
      '    at async DevServer.handleRequest (/Users/like/repo/tmp/trpc-minimal-starter-issue-demo/node_modules/next/dist/server/base-server.js:322:20)',
    path: 'greeting'
  },
  [cause]: undefined
}
``` 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
This is not tRPC-related. we don't do anything with your build time that could possibly affect this.

**Comment by ekil1100** [comment]
@KATT Sorry, I didn't catch your point. The reproduction is clean and cloned from examples-next-minimal-starter. The ramda is works fine else where except in trpc query function.
