### ISSUE TITLE
bug: when publicProcedure is exported from a different file it is undefined in cloudflare worker env

### ISSUE THREAD

**Issue by MaazDev** [trpc/trpc#3596]
### Provide environment information

  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
    Memory: 5.24 GB / 15.96 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE     
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @trpc/server: ^10.8.1 => 10.8.1
    typescript: ^4.9.4 => 4.9.4

### Describe the bug

when using publicProcedure declared from inside the same file it's being used everything works fine but when I import publicProcedure from another file I get the error
` TypeError: Cannot read properties of undefined (reading 'query')
    at C:\Users\m\AppData\Desktop\trpc_worker\src\router.ts:17:33
    at SourceTextModule.evaluate (node:internal/vm/module:226:23)
    at VMScriptRunner.runAsModule (C:\Users\m\Desktop\trpc_worker\node_modules\@miniflare\runner-vm\src\index.ts:38:18)
    at VMScriptRunner.run (C:\Users\m\Desktop\trpc_worker\node_modules\@miniflare\runner-vm\src\index.ts:82:17)
    at Miniflare.#reload (C:\Users\m\Desktop\trpc_worker\node_modules\@miniflare\core\src\index.ts:775:13)
    at Miniflare.getPlugins (C:\Users\m\Desktop\trpc_worker\node_modules\@miniflare\core\src\index.ts:1017:5)
    at createServer (C:\Users\m\Desktop\trpc_worker\node_modules\@miniflare\http-server\src\index.ts:369:19)
    at startServer (C:\Users\m\Desktop\trpc_worker\node_modules\@miniflare\http-server\src\index.ts:476:18)
    at main (file:///C:/Users/m/Desktop/trpc_worker/node_modules/wrangler/miniflare-dist/index.mjs:6283:22)
    at file:///C:/Users/m/Desktop/trpc_worker/node_modules/wrangler/miniflare-dist/index.mjs:6351:1
`

the same goes with router etc..

### Link to reproduction

https://github.com/MaazDev/trpc_cloudflare_error/

### To reproduce

1. wrangler init test
2. in src/index.ts past this

```
import { fetchRequestHandler } from '@trpc/server/adapters/fetch';
import { appRouter } from './router';
import {initTRPC} from "@trpc/server";

export const t = initTRPC.create();

export const publicProcedure = t.procedure;
export const router = t.router;

export default {
	async fetch(request: Request): Promise<Response> {
		return fetchRequestHandler({
			endpoint: '/trpc',
			req: request,
			router: appRouter,
			createContext: () => ({}),
		});
	},
};
```
3. in src/router.ts pas this code
```
import {publicProcedure, router} from "./index";
export const appRouter = router({
    hello: publicProcedure.query(() => "hello")
});

export type AppRouter = typeof appRouter;
```
4. run wrangler dev
5. press l to go in local mode and get more info about the error

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Not a big, it's a circular dep that JS doesn't understand

https://github.com/trpc/trpc/discussions/3582#discussioncomment-4639075
