### ISSUE TITLE
bug: trpc.middleware is not a function

### ISSUE THREAD

**Issue by anuragkumar19** [trpc/trpc#3944]
### Provide environment information

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz    
    Memory: 465.48 MB / 3.84 GB
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 110.0.5481.178
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.57)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    typescript: ^4.9.5 => 4.9.5 
```

### Describe the bug

Full code: https://github.com/anuragkumar19/telecord-trpc-nuxt3

```typescript
// file: middleware/auth.ts
// ...
export const authGuardTRPC = middleware(async ({ ctx, next }) => {
    const token = ctx.req.headers.authorization

    const user = await getUserFromToken(token)

    return next({
        ctx: {
            ...ctx,
            user,
        },
    })
});
```

Error:
```server:dev: C:\Project\telecord\telecord\backend\apps\server\dist\middleware\auth.js:43
server:dev: exports.authGuardTRPC =  trpc_1.middleware(async ({ ctx, next }) => {
server:dev:                                 ^
server:dev: 
server:dev: TypeError: trpc_1.middleware is not a function
server:dev:     at Object.<anonymous> (C:\Project\telecord\telecord\backend\apps\server\dist\middleware\auth.js:43:33)   
server:dev:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
server:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
server:dev:     at Module.load (node:internal/modules/cjs/loader:1117:32)
server:dev:     at Module._load (node:internal/modules/cjs/loader:958:12)
server:dev:     at Module.require (node:internal/modules/cjs/loader:1141:19)
server:dev:     at require (node:internal/modules/cjs/helpers:110:18)
server:dev:     at Object.<anonymous> (C:\Project\telecord\telecord\backend\apps\server\dist\trpc.js:5:16)
server:dev:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
server:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
server:dev:
server:dev: Node.js v18.14.2

```
Typescript is giving no error but after compiling node.js is throwing this error.

### Link to reproduction

https://stackblitz.com/edit/typescript-ahnlxt

### To reproduce

Run:
```
pnpm watch
pnpm dev
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Remove the circular reference between 

https://github.com/anuragkumar19/telecord-trpc-nuxt3/blob/main/apps/server/src/trpc.ts and https://github.com/anuragkumar19/telecord-trpc-nuxt3/blob/main/apps/server/src/middleware/auth.ts
