### ISSUE TITLE
bug: trpc-prisma-websockets-starter post.infinite fails on page load

### ISSUE THREAD

**Issue by HartS** [trpc/trpc#4063]
### Provide environment information

```
  System:
    OS: macOS 11.7.4
    CPU: (8) x64 Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz
    Memory: 72.72 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  npmPackages:
    @tanstack/react-query: ^4.18.0 => 4.28.0
    @trpc/client: ^10.18.0 => 10.18.0
    @trpc/next: ^10.18.0 => 10.18.0
    @trpc/react-query: ^10.18.0 => 10.18.0
    @trpc/server: ^10.18.0 => 10.18.0
    next: ^13.2.1 => 13.2.4
    react: ^18.2.0 => 18.2.0
    typescript: ^4.8.3 => 4.9.5
```

### Describe the bug

When running the next websocket next sample app, the call to `post.infinite` when the page loads doesn't actually send a websocket frame, but I see this error in the console:

```✅ WebSocket Server listening on ws://localhost:3001
➕➕ Connection (1)
(node:14403) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
createContext for test
 << query #1 post.infinite {
  input: { cursor: undefined },
  result: TRPCClientError: fetch failed
      at TRPCClientError.from (file:///Users/hartsimha/Desktop/development/git/trpc-prisma-websockets-starter/node_modules/.pnpm/@trpc+client@10.18.0_@trpc+server@10.18.0/node_modules/@trpc/client/dist/transformResult-6fb67924.mjs:13:16)
      at file:///Users/hartsimha/Desktop/development/git/trpc-prisma-websockets-starter/node_modules/.pnpm/@trpc+client@10.18.0_@trpc+server@10.18.0/node_modules/@trpc/client/dist/links/httpBatchLink.mjs:200:64 {
    meta: undefined,
    shape: undefined,
    data: undefined,
    [cause]: TypeError: fetch failed
        at Object.fetch (node:internal/deps/undici/undici:11118:11) {
      cause: [InvalidArgumentError]
    }
  },
  elapsedMs: 4,
  context: {}
}
TRPCClientError: fetch failed
    at TRPCClientError.from (file:///Users/hartsimha/Desktop/development/git/trpc-prisma-websockets-starter/node_modules/.pnpm/@trpc+client@10.18.0_@trpc+server@10.18.0/node_modules/@trpc/client/dist/transformResult-6fb67924.mjs:13:16)
    at file:///Users/hartsimha/Desktop/development/git/trpc-prisma-websockets-starter/node_modules/.pnpm/@trpc+client@10.18.0_@trpc+server@10.18.0/node_modules/@trpc/client/dist/links/httpBatchLink.mjs:200:64 {
  meta: undefined,
  shape: undefined,
  data: undefined,
  [cause]: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11118:11) {
    cause: InvalidArgumentError: invalid connection header
        at processHeader (node:internal/deps/undici/undici:6504:15)
        at new Request (node:internal/deps/undici/undici:6387:13)
        at [dispatch] (node:internal/deps/undici/undici:7359:25)
        at Client.Intercept (node:internal/deps/undici/undici:7119:20)
        at Client.dispatch (node:internal/deps/undici/undici:429:44)
        at [dispatch] (node:internal/deps/undici/undici:648:32)
        at Pool.dispatch (node:internal/deps/undici/undici:429:44)
        at [dispatch] (node:internal/deps/undici/undici:8649:27)
        at Agent.Intercept (node:internal/deps/undici/undici:7119:20)
        at Agent.dispatch (node:internal/deps/undici/undici:429:44)
        at node:internal/deps/undici/undici:11010:83
        at new Promise (<anonymous>)
        at dispatch (node:internal/deps/undici/undici:11010:16)
        at httpNetworkFetch (node:internal/deps/undici/undici:10917:65)
        at httpNetworkOrCacheFetch (node:internal/deps/undici/undici:10819:39)
        at httpFetch (node:internal/deps/undici/undici:10671:43)
        at schemeFetch (node:internal/deps/undici/undici:10607:24)
        at node:internal/deps/undici/undici:10483:26
        at mainFetch (node:internal/deps/undici/undici:10500:11)
        at fetching (node:internal/deps/undici/undici:10457:7)
        at Agent.fetch2 (node:internal/deps/undici/undici:10337:20)
        at Object.fetch (node:internal/deps/undici/undici:11116:28)
        at fetch (node:internal/process/pre_execution:216:25)
        at file:///Users/hartsimha/Desktop/development/git/trpc-prisma-websockets-starter/node_modules/.pnpm/@trpc+client@10.18.0_@trpc+server@10.18.0/node_modules/@trpc/client/dist/httpUtils-9b676ab4.mjs:92:25 {
      code: 'UND_ERR_INVALID_ARG'
    }
  }
}
```

Due to how react-query `useInfiniteQuery` works, it attempts a refetch when the window is unfocused and then focused, which then gets the data and populates the main chat section with the chat history

I added some logging of the `postsQuery` object: https://github.com/trpc/examples-next-prisma-websockets-starter/blob/main/src/pages/index.tsx#L115 

```
  useEffect(() => {
    const { isFetching, isRefetching, isStale, status, fetchStatus, error } =
      postsQuery;
    console.log(isFetching, isRefetching, isStale, status, fetchStatus, error.message);
  }, [postsQuery]);
  ```

which prints out the following:

```
false false true error idle "fetch failed"
```

Not sure how to debug this further, but I'd really love to see the infinite query working.

### Link to reproduction

N/A

### To reproduce

1. Run the following startup commands:

```
pnpm create next-app --example https://github.com/trpc/trpc --example-path examples/next-prisma-websockets-starter trpc-prisma-websockets-starter
cd trpc-prisma-websockets-starter
sed -i '' 's/5432/5932/g' "env # replaces port reference in file so postgres can be reached
pnpm i
pnpm dx
```

2. Navigate to localhost:3000
3. Send a chat message
4. Refresh page
5. switch to another tab, then back

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Upgrade node to latest or omit the `connection` header as specified here: https://trpc.io/docs/nextjs/ssr

**Comment by HartS** [comment]
Thanks @KATT . It's occurred to me now that I can't find any documentation on the oldest version trpc can work with. Any idea about this? Will it work on, say, v16 or v14? Heck, maybe even as far back as v10?

Definitely fine if you don't know, I'm happy to try it on different versions with some workarounds

**Comment by KATT** [comment]
Officially node 14, but we'll stop supporting that in the next major as it's closing end of life.

Feel free to update the docs or website in the appropriate place.

Assuming this is resolved. Closing
