### ISSUE TITLE
feat: Improve Error message when logging router

### ISSUE THREAD

**Issue by hyperupcall** [trpc/trpc#4119]
### Describe the feature you'd like to request

Currently, when logging a router to the console, a mysterious error is shown to the console

```ts
export const trpc = initTRPC.context<typeof createContext>().create();
console.log(trpc.router({}))
```

```txt
error: Uncaught (in promise) Error: Tried to access "$types.name" which is not available at runtime
        throw new Error(`Tried to access "$types.${key}" which is not available at runtime`);
              ^
    at https://esm.sh/v113/@trpc/server@10.11.0/deno/server.development.mjs:1064:15
    at Object.get (https://esm.sh/v113/@trpc/server@10.11.0/deno/server.development.mjs:120:14)
    at inspectFunction (ext:deno_console/02_console.js:389:13)
    at _inspectValue (ext:deno_console/02_console.js:709:14)
    at inspectValue (ext:deno_console/02_console.js:737:9)
    at inspectValueWithQuotes (ext:deno_console/02_console.js:854:14)
    at inspectRawObject (ext:deno_console/02_console.js:1237:13)
    at inspectObject (ext:deno_console/02_console.js:1414:36)
    at _inspectValue (ext:deno_console/02_console.js:719:14)
    at inspectValue (ext:deno_console/02_console.js:737:9)
```

I've encountered this error twice, and unfortunately, I forgot what caused it the second time around. Maybe this error message can be improved so other people don't make the same mistake as I did.

### Describe the solution you'd like to see

Maybe include something like `"are you printing a router?"` to the console

### Describe alternate solutions

Not improving the error message

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by kamilogorek** [comment]
Note: This is Deno-only issue.

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/1523305/229121923-3fd8ed87-c14d-4117-9e8e-63aa066537ae.png">

**Comment by sachinraja** [comment]
This is a Deno issue, tracked at https://github.com/denoland/deno/issues/12926
