### ISSUE TITLE
feat: Support react-query@5 and edge

### ISSUE THREAD

**Issue by Thinkscape** [trpc/trpc#4218]
### Describe the feature you'd like to request

So `react-query` [just had a new major version bump](https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5) which removes some react kludge, which hopefully will make it tRPC + query compatible with edge runtimes (i.e. CF workers, Vercel edge etc.)

### Describe the solution you'd like to see

https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5 describes migration steps. Would need some updates to `@trpc/next`.

### Describe alternate solutions

I believe there's nothing inherently breaking on edge runtimes in `@trpc/next`, so it's up to `react-query`.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by Thinkscape** [comment]
I'm on the fence if that should be tossed over to #3496.
Because react-query is a dependency, I think that would be a minor update to `@trpc/next`.

**Comment by KATT** [comment]
@TkDodo you think we could alias a bunch of old old APIs for compatibility with trpc?

Maybe do a `/compat`-module that exists in both v4 and v5 that we can target

**Comment by rawsh** [comment]
This is a major blocker for running on cloudflare Pages, would be willing to work on a PR for this

**Comment by AlonMiz** [comment]
hopefully, react query 5 will allow supporting edge. I am waiting for that. 🙏

**Comment by faradaytrs** [comment]
React query entered beta and hopefully will be released soon

**Comment by estubmo** [comment]
I would appreciate a status update on this

**Comment by estubmo** [comment]
I suppose it was just added in this PR: https://github.com/trpc/trpc/pull/4662

**Comment by teddybee** [comment]
react-query v5 rc1 has been out

**Comment by faradaytrs** [comment]
React query released, any plan for new version supporting it?

**Comment by juliusmarminge** [comment]
Use the @next tag

We're still a bit away from v11 but the next tag has rq5 as peerDep

**Comment by doneumark** [comment]
Hey. Any news when will @trpc/react-query will support react-query in a release?

**Comment by juliusmarminge** [comment]
> Hey. Any news when will @trpc/react-query will support react-query in a release?

v11

release date unknown, use next tag for now:

```json
    "@tanstack/react-query": "^5.0.5",
    "@trpc/client": "next",
    "@trpc/react-query": "next",
    "@trpc/server": "next",
```

**Comment by doneumark** [comment]
Thanks @juliusmarminge !
Updating to this makes my app throw an error:
` ⨯ node_modules/@trpc/client/dist/TRPCClientError-0de4d231.mjs (37:15) @ TRPCClientError.from
 ⨯ Internal error: TRPCClientError: fetch failed
    at TRPCClientError.from (./node_modules/@trpc/client/dist/TRPCClientError-0de4d231.mjs:41:16)
    at eval (./node_modules/@trpc/client/dist/httpBatchLink-204206a5.mjs:207:101)
Cause: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:14294:11) {
  cause: InvalidArgumentError: invalid connection header`

**Comment by juliusmarminge** [comment]
> cause: InvalidArgumentError: invalid connection header

What node version? You need to omit the connection header for certain node versions, but I can't see why updating to v11 would cause that if it wasn't there before...

**Comment by doneumark** [comment]
> > cause: InvalidArgumentError: invalid connection header
> 
> What node version? You need to omit the connection header for certain node versions, but I can't see why updating to v11 would cause that if it wasn't there before...

node/19.1.0

**Comment by teddybee** [comment]
> node/19.1.0. Also, it didn't worked before, its a brand new project created with t3-stack, for testing the new next 14 with trpc.

Use Node 20, its LTS now.

**Comment by doneumark** [comment]
> > node/19.1.0. Also, it didn't worked before, its a brand new project created with t3-stack, for testing the new next 14 with trpc.
> 
> Use Node 20, its LTS now.

you are very much correct :)
Thank you all! @teddybee @juliusmarminge

**Comment by Senbonzakura1234** [comment]
> > Hey. Any news when will @trpc/react-query will support react-query in a release?
> 
> v11
> 
> release date unknown, use next tag for now:
> 
> ```json
>     "@tanstack/react-query": "^5.0.5",
>     "@trpc/client": "next",
>     "@trpc/react-query": "next",
>     "@trpc/server": "next",
> ```
@juliusmarminge 
Got `Cannot find module '@trpc/react-query' or its corresponding type declarations.` error when trying this

**Comment by crivera** [comment]
any idea when this will be pushed?

**Comment by melodyclue** [comment]
Is trpc not compatible with tanstack5 after all?

**Comment by TkDodo** [comment]
>  Is trpc not compatible with tanstack5 after all?

v11 is

**Comment by KATT** [comment]
> Is trpc not compatible with tanstack5 after all?

@melodyclue (how) did you miss the massive ℹ️  in the description above? 😅

**Comment by melodyclue** [comment]
@KATT  Sorry, I'm new to issues, what is massive ℹ️?

**Comment by Senbonzakura1234** [comment]
> @KATT Sorry, I'm new to issues, what is massive ℹ️?

Read the top comment

**Comment by KATT** [comment]
https://trpc.io/docs/migrate-from-v10-to-v11
