### ISSUE TITLE
bug: Next.js 13.4 build errors

### ISSUE THREAD

**Issue by JoeKarow** [trpc/trpc#4316]
### Provide environment information

```
  System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 216.73 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/Library/Caches/fnm_multishells/7767_1683126064680/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/7767_1683126064680/bin/npm
  Browsers:
    Brave Browser: 107.1.45.127
    Chrome: 109.0.5414.119
    Firefox: 106.0
    Safari: 16.4
  npmPackages:
    @tanstack/react-query: 4.29.5 => 4.29.5
    @trpc/client: 10.25.0 => 10.25.0
    @trpc/next: 10.25.0 => 10.25.0
    @trpc/react-query: 10.25.0 => 10.25.0
    @trpc/server: 10.25.0 => 10.25.0
    next: 13.4.0 => 13.4.0
    react: 18.2.0 => 18.2.0
    typescript: 5.0.4 => 5.0.4
```

### Describe the bug

Upgrading Next.js to 13.4 causes the project to not build.
The following error was repeated for several different routes:

<details>
<summary>Build Error (single example)</summary>

```sh
Error occurred prerendering page "/profile". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of null (reading 'useMemo')
    at exports.useMemo (/Users/joe/GitHub/InReach/monorepo/node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react.production.min.js:25:208)
    at Object.useDehydratedState (file:///Users/joe/GitHub/InReach/monorepo/node_modules/.pnpm/@trpc+react-query@10.25.0_@tanstack+react-query@4.29.5_@trpc+client@10.25.0_@trpc+server@10.2_g6kbjzangqetmhsdt26x4s6jva/node_modules/@trpc/react-query/dist/createHooksInternal-ac3d45d9.mjs:517:29)
    at WithTRPC (/Users/joe/GitHub/InReach/monorepo/apps/app/.next/server/chunks/248.js:13429:38)
    at Ge (/Users/joe/GitHub/InReach/monorepo/node_modules/.pnpm/next@13.4.0_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:273)
    at Z (/Users/joe/GitHub/InReach/monorepo/node_modules/.pnpm/next@13.4.0_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
    at Ge (/Users/joe/GitHub/InReach/monorepo/node_modules/.pnpm/next@13.4.0_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
    at Z (/Users/joe/GitHub/InReach/monorepo/node_modules/.pnpm/next@13.4.0_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
    at He (/Users/joe/GitHub/InReach/monorepo/node_modules/.pnpm/next@13.4.0_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:123:155)
    at Je (/Users/joe/GitHub/InReach/monorepo/node_modules/.pnpm/next@13.4.0_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:122:100)
    at Z (/Users/joe/GitHub/InReach/monorepo/node_modules/.pnpm/next@13.4.0_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:222)
```

Summary of route errors:

```sh
> Export encountered errors on following paths:
	/_error: /404
	/_error: /500
	/_error: /ar/404
	/_error: /ar/500
	/_error: /en/404
	/_error: /en/500
	/_error: /es/404
	/_error: /es/500
	/_error: /fr/404
	/_error: /fr/500
	/_error: /ru/404
	/_error: /ru/500
	/profile
	/profile: /ar/profile
	/profile: /en/profile
	/profile: /es/profile
	/profile: /fr/profile
	/profile: /ru/profile
	/search
	/search: /ar/search
	/search: /en/search
	/search: /es/search
	/search: /fr/search
	/search: /ru/search
```

</details>

Removing the `withTRPC`	wrapper in `_app.tsx` allows the build to succeed. 

### Link to reproduction

https://github.com/weareinreach/InReach/tree/renovate/next.js

### To reproduce

Run `pnpm build` from the `apps/app` directory in the monorepo.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
My hunch is that we need to output `"use client"` in the build
