### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by jonathanrgreene** [trpc/trpc#4694]
### Provide environment information

 System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 344.19 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /opt/local/bin/node
    Yarn: 1.22.19 - /opt/local/bin/yarn
    npm: 8.5.5 - /opt/local/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Edge: 114.0.1823.67
    Safari: 16.1
  npmPackages:
    @trpc/client: ^10.37.1 => 10.37.1 
    @trpc/server: ^10.37.1 => 10.37.1 
    typescript: ~4.5.4 => 4.5.5 

### Describe the bug

I can't seem to get webpack to handle this:
import { createHTTPServer } from '@trpc/server/dist/adapters/standalone';

I can't figure out how to do this in stackblitz, but you can recreate pretty easily...

1) Start out with electron using the webpack typescript template.
`npm init electron-app@latest my-new-app -- --template=webpack-typescript`

2) Install trpc....
`npm install @trpc/server @trpc/client`

3) Try to import the adapter in index.ts ...
`import { createHTTPServer } from '@trpc/server/dist/adapters/standalone';`

4) Just console log createHTTPServer so it doesn't complain about being unused ...
`console.log(createHTTPServer);`

5) Run electron ...
`npm run start`

That's it. Now you get this ...

```
> my-new-app@1.0.0 start
> electron-forge start

✔ Checking your system
✔ Locating application
✔ Loading configuration
✔ Preparing native dependencies [0.1s]
✔ Running generateAssets hook
✔ [plugin-webpack] Compiling main process code [0.2s]
✔ [plugin-webpack] Launching dev servers for renderer process code [0.3s]
  › Output Available: http://localhost:9000

App threw an error during load
Error: Cannot find module '@trpc/server/dist/adapters/standalone'
    at webpackMissingModule (/Users/###/Documents/Code/my-new-app/.webpack/main/index.js:1017:91)
    at /Users/###/Documents/Code/my-new-app/.webpack/main/index.js:1017:203
    at /Users/###/Documents/Code/my-new-app/.webpack/main/index.js:1059:3
    at Object.<anonymous> (/Users/###/Documents/Code/my-new-app/.webpack/main/index.js:1062:12)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at loadApplicationPackage (/Users/cardiex/Documents/Code/my-new-app/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:121:16)
```

My package.json ...
```
{
  "name": "my-new-app",
  "productName": "my-new-app",
  "version": "1.0.0",
  "description": "My Electron application description",
  "main": ".webpack/main",
  "scripts": {
    "start": "electron-forge start",
    "package": "electron-forge package",
    "make": "electron-forge make",
    "publish": "electron-forge publish",
    "lint": "eslint --ext .ts,.tsx ."
  },
  "keywords": [],
  "license": "MIT",
  "devDependencies": {
    "@electron-forge/cli": "^6.2.1",
    "@electron-forge/maker-deb": "^6.2.1",
    "@electron-forge/maker-rpm": "^6.2.1",
    "@electron-forge/maker-squirrel": "^6.2.1",
    "@electron-forge/maker-zip": "^6.2.1",
    "@electron-forge/plugin-auto-unpack-natives": "^6.2.1",
    "@electron-forge/plugin-webpack": "^6.2.1",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "@vercel/webpack-asset-relocator-loader": "1.7.3",
    "css-loader": "^6.0.0",
    "electron": "25.4.0",
    "eslint": "^8.0.1",
    "eslint-plugin-import": "^2.25.0",
    "fork-ts-checker-webpack-plugin": "^7.2.13",
    "node-loader": "^2.0.0",
    "style-loader": "^3.0.0",
    "ts-loader": "^9.2.2",
    "ts-node": "^10.0.0",
    "typescript": "~4.5.4"
  },
  "dependencies": {
    "@trpc/client": "^10.37.1",
    "@trpc/server": "^10.37.1",
    "electron-squirrel-startup": "^1.0.0"
  }
}

```

### Link to reproduction

See above.

### To reproduce

See above.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4694">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4694/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4694/pledge.svg">
</picture>
</a>

**Comment by jonathanrgreene** [comment]
Ok I realized what I did wrong. You'd think I'd figure it out by opening my eyes and looking... but nope, I ran Webpack manually with debug logging and saw that `'@trpc/server/dist/adapters/standalone'` isn't exported by @trpc. Why? Because it's exported as `'@trpc/server/adapters/standalone'`. -_- Duh.

Hopefully someone else lacking in coffee will see this and realize their folly.
