### ISSUE TITLE
bug: TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_3__.createContext) is not a function

### ISSUE THREAD

**Issue by garrettg123** [trpc/trpc#4957]
### Provide environment information

```
  System:
    OS: macOS 13.4.1
    CPU: (12) x64 Apple M2 Max
    Memory: 433.87 MB / 32.00 GB
    Shell: 3.6.1 - /usr/local/bin/fish
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm
    pnpm: 8.6.12 - ~/Library/pnpm/pnpm
    Watchman: 2023.08.14.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 16.5.1
  npmPackages:
    @tanstack/react-query: ^4.36.1 => 4.36.1
    @trpc/client: ^10.42.0 => 10.42.0
    @trpc/next: ^10.42.0 => 10.42.0
    @trpc/react-query: ^10.42.0 => 10.42.0
    @trpc/server: ^10.42.0 => 10.42.0
    next: ^13.5.6 => 13.5.6
    react: 18.2.0 => 18.2.0
    typescript: ^5.1.6 => 5.2.2
```

### Describe the bug

When starting my NextJS server with `next dev` I see this error.

### Link to reproduction

https://stackblitz.com/edit/github-8u4cxv?file=package.json

### To reproduce

Run a NextJS/tRPC app with those versions
The app runs, but NextJS keeps reloading on every save and I think this is why.
The demo is breaking for a different reason, not sure why.

### Additional information

```
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_3__.createContext) is not a function
    at eval (webpack-internal:///(rsc)/./node_modules/@trpc/react-query/dist/createHooksInternal-bdff7171.mjs:105:87)
    at (rsc)/./node_modules/@trpc/react-query/dist/createHooksInternal-bdff7171.mjs (/Users/gsquare567/Sites/pulse/.next/server/vendor-chunks/@trpc.js:120:1)
    at __webpack_require__ (/Users/gsquare567/Sites/pulse/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/@trpc/react-query/dist/index.mjs:26:91)
    at (rsc)/./node_modules/@trpc/react-query/dist/index.mjs (/Users/gsquare567/Sites/pulse/.next/server/vendor-chunks/@trpc.js:140:1)
    at __webpack_require__ (/Users/gsquare567/Sites/pulse/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/@trpc/next/dist/index.mjs:9:75)
    at (rsc)/./node_modules/@trpc/next/dist/index.mjs (/Users/gsquare567/Sites/pulse/.next/server/vendor-chunks/@trpc.js:110:1)
    at __webpack_require__ (/Users/gsquare567/Sites/pulse/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/utils/api.ts:6:68)
    at (rsc)/./src/utils/api.ts (/Users/gsquare567/Sites/pulse/.next/server/app/not-found.js:141:1)
    at __webpack_require__ (/Users/gsquare567/Sites/pulse/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/layout.tsx:9:68)
    at (rsc)/./src/app/layout.tsx (/Users/gsquare567/Sites/pulse/.next/server/app/not-found.js:130:1)
    at Function.__webpack_require__ (/Users/gsquare567/Sites/pulse/.next/server/webpack-runtime.js:33:42)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async e_ (/Users/gsquare567/Sites/pulse/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:455780)
    at async eJ (/Users/gsquare567/Sites/pulse/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:459720)
    at async eY (/Users/gsquare567/Sites/pulse/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:460227)
    at async eK (/Users/gsquare567/Sites/pulse/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:463770)
    at async /Users/gsquare567/Sites/pulse/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:464248 {
  digest: '2141116735'
}
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4957">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4957/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4957/pledge.svg">
</picture>
</a>

**Comment by Nick-Lucas** [comment]
Hi, I've seen this in the help channels from a few people now, so suspect there _is_ a problem somewhere in the toolchain, whether that's tRPC's fault or a Next.JS thing

That stackblitz though unfortunately doesn't show a reproduction, it just fails to install SWC during setup.

I've disabled SWC and enabled babel in [this fork](https://stackblitz.com/edit/github-8u4cxv-lcuq43?file=src%2Futils%2Ftrpc.ts) but then the app does build/run and just has some networking issue. So I don't believe that's a reproduction either. If that's got past the point you were getting this error, then it might point to a problem with SWC

**Comment by jmsv** [comment]
I'm getting a similar error with node v20.9.0 and the following deps:

```json
{
  "next": "14.0.0",
  "@trpc/client": "10.37.1",
  "@trpc/next": "10.37.1",
  "@trpc/react-query": "10.37.1",
  "@trpc/server": "10.37.1"
}
```

```
SyntaxError: Named export 'createContext' not found. The requested module 'react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react';
const { createContext, useRef, useState, useEffect, useCallback, useMemo } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15)
 ⨯ file:///app/node_modules/@trpc/react-query/dist/createHooksInternal-bdff7171.mjs:5
import React, { createContext, useRef, useState, useEffect, useCallback, useMemo } from 'react';
                ^^^^^^^^^^^^^
```

The file mentioned: https://unpkg.com/browse/@trpc/react-query@10.43.0/dist/createHooksInternal-bdff7171.mjs

Weirdly, I don't get this error on `next dev` or `next build`, but when the server boots up in Docker on `node:20-alpine` using a Dockerfile based on this example: https://github.com/vercel/turbo/blob/main/examples/with-docker/apps/web/Dockerfile

**Comment by gauravburjwal** [comment]
I am also getting the same error and using the following dependencies

```
"@tanstack/react-query": "^4.36.1",
"@trpc/client": "^10.43.0",
"@trpc/next": "^10.43.0",
"@trpc/react-query": "^10.43.0",
"@trpc/server": "^10.43.0",
"next": "14.0.0",
"typescript": "^5"
"react": "^18",
"react-dom": "^18",
```

**Comment by aomi** [comment]
Updating to 14.0.1 fixed the issue for us. 
https://github.com/vercel/next.js/releases/tag/v14.0.1
```
    "@tanstack/react-query": "^4.33.0",
    "@trpc/client": "^10.37.1",
    "@trpc/next": "^10.37.1",
    "@trpc/react-query": "^10.37.1",
    "@trpc/server": "^10.37.1",
    "next": "^14.0.1",
```

**Comment by kirillrogovoy** [comment]
> Updating to Next 14.0.1 fixed the issue for us.

Same here: 14.0.0 produced the error, 14.0.1 is working fine.

**Comment by cgav** [comment]
@Nick-Lucas I created a repro repo here: https://github.com/cgav/next-trpc/tree/main. Running it via `bun i` and `bun dev` throws the error described above.

**Comment by moigithub** [comment]
had same problem... 
added "use client" and error gone

**Comment by KATT** [comment]
This appears to be an error to do with missing `"use client"` directives indeed and not related to trpc itself.

See here what I did to fix it on @cgav's repro: https://github.com/cgav/next-trpc/pull/1


If I'm wrong, feel free to re-open the issue.
