### ISSUE TITLE
bug: Cannot access 'routeName' before initialization

### ISSUE THREAD

**Issue by ahkhanjani** [trpc/trpc#4971]
### Provide environment information

 System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 10.22 GB / 19.84 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.5.0 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (118.0.2088.69)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @tanstack/react-query: ^4.36.1 => 4.36.1 
    @trpc/client: ^10.43.0 => 10.43.0 
    @trpc/next: ^10.43.0 => 10.43.0 
    @trpc/react-query: ^10.43.0 => 10.43.0 
    @trpc/server: ^10.43.0 => 10.43.0 
    next: ^13.5.6 => 13.5.6 
    react: ^18.2.0 => 18.2.0 
    typescript: ^5.2.2 => 5.2.2

### Describe the bug

I recently changed the structure of my routers from being flat (root -> router -> procedure) to nested (root -> (variable depth routers) -> procedure) and while it works perfectly fine for any other router, one of my routers throws this error:

```
ReferenceError: Cannot access 'exampleRouter' before initialization
    at Module.exampleRouter(webpack-internal:///(api)/./src/server/api/routers/live/quiz/multi-choice.ts:4:59)
    at eval (webpack-internal:///(api)/./src/server/api/routers/live/quiz/index.ts:33:61)
    at (api)/./src/server/api/routers/live/quiz/index.ts (xxx\.next\server\pages\api\trpc\[trpc].js:382:1)
    at __webpack_require__ (xxx\.next\server\webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./src/server/api/routers/live/quiz/multi-choice.ts:17:59)
    at (api)/./src/server/api/routers/live/quiz/multi-choice.ts (xxx\.next\server\pages\api\trpc\[trpc].js:402:1)
    at __webpack_require__ (xxx\.next\server\webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./src/server/api/routers/live/state.ts:17:76)
    at (api)/./src/server/api/routers/live/state.ts (xxx\.next\server\pages\api\trpc\[trpc].js:412:1)
    at __webpack_require__ (xxx\.next\server\webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./src/server/api/routers/live/index.ts:7:64)
    at (api)/./src/server/api/routers/live/index.ts (xxx\.next\server\pages\api\trpc\[trpc].js:352:1)
    at __webpack_require__ (xxx\.next\server\webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./src/server/api/root.ts:9:82)
    at (api)/./src/server/api/root.ts (xxx\.next\server\pages\api\trpc\[trpc].js:332:1)
```

I tried to debug or log my root router to see the value of that one router at runtime. Debugger didn't work so I wrote a `console.log` of my root router in my next-auth sign in callback so that it can run on the server. And to my surprise, the `console.log` made it work again. So for some reason, that router is not initialized automatically and my `console.log` makes it initialize.

This can just be me doing something stupid, so I'll create a repo soon. Another thing is that, I have another almost identical router right next to it and it works. I tried to change their order in different combinations and it doesn't make a difference.

I'm sorry for my vague description without an example. For now I'm just wondering if there is any known bugs that could possibly cause this. I would also appreciate an example repo of a deeply nested router, as it's missing in the documentation.

### Link to reproduction

will add soon

### To reproduce

Not sure yet

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by juliusmarminge** [comment]
Probably got some circular import thingy going on. Can't say more than that without a reproduction repo

**Comment by ahkhanjani** [comment]
> Probably got some circular import thingy going on. Can't say more than that without a reproduction repo

I'm really trying to repro this and it doesn't work. So it's definitely a problem with my code. It acts differently each time I boot up the server. After I did that import in next-auth trick, it gives me another error: `Cannot access 'createTRPCRouter' before initialization`.

What kind of circular import are we talking about? Could you please provide an example? @juliusmarminge
