### ISSUE TITLE
bug:  tRPC not working in Next.js 14 despite following documentation setup instructions - No QueryClient set error

### ISSUE THREAD

**Issue by junya-ishibuchi** [trpc/trpc#5014]
### Provide environment information

```
  System:
    OS: macOS 14.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 4.78 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.18 - /opt/homebrew/bin/npm
    pnpm: 8.10.2 - /opt/homebrew/bin/pnpm
    bun: 1.0.7 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.105
    Safari: 17.1
  npmPackages:
    @tanstack/react-query: ^5.8.1 => 5.8.1
    @trpc/client: ^10.43.1 => 10.43.1
    @trpc/next: ^10.43.1 => 10.43.1
    @trpc/react-query: ^10.43.1 => 10.43.1
    @trpc/server: ^10.43.1 => 10.43.1
    next: 14.0.1 => 14.0.1
    react: ^18 => 18.2.0
    typescript: ^5 => 5.2.2
```

### Describe the bug

I've encountered an issue while trying to set up tRPC(10.43.1) in a Next.js(14.0.1) project by following the instructions provided on the [tRPC Next.js setup page](https://trpc.io/docs/client/nextjs/setup).
Despite following the setup steps carefully, I'm facing an error that is preventing the application from functioning properly.
This error appears every time I try to run a query using tRPC. 

Here is the code where the error is occurring.
```tsx
src/pages/index.tsx (4:27) @ useQuery

  2 |
  3 | export default function IndexPage() {
> 4 | const hello = trpc.hello.useQuery({ text: 'client' });
    |                         ^
  5 | if (!hello.data) {
  6 |   return <div>Loading...</div>;
  7 | }
```

And, the specific error message I receive in the console is:
```
Error: No QueryClient set, use QueryClientProvider to set one
at useQueryClient (.../bug-trpc/node_modules/@trpc/react-query/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:35:11)
at useBaseQuery (.../bug-trpc/node_modules/@trpc/react-query/node_modules/@tanstack/react-query/build/lib/useBaseQuery.mjs:12:23)
at useQuery (.../bug-trpc/node_modules/@trpc/react-query/node_modules/@tanstack/react-query/build/lib/useQuery.mjs:7:10)
at Object.useQuery$1 [as useQuery] (.../bug-trpc/node_modules/@trpc/react-query/dist/createHooksInternal-bdff7171.mjs:370:22)
                                      at .../bug-trpc/node_modules/@trpc/react-query/dist/createHooksInternal-bdff7171.mjs:76:30
  at Object.apply (.../bug-trpc/node_modules/@trpc/server/dist/index-f91d720c.mjs:67:20)
at IndexPage (webpack-internal:///./src/pages/index.tsx:14:71)
at renderWithHooks (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
at renderIndeterminateComponent (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
at renderElement (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
at renderNodeDestructiveImpl (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
at renderNodeDestructive (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
at renderIndeterminateComponent (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
at renderElement (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
at renderNodeDestructiveImpl (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
⨯ Error: No QueryClient set, use QueryClientProvider to set one
at useQueryClient (.../bug-trpc/node_modules/@trpc/react-query/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:35:11)
at useBaseQuery (.../bug-trpc/node_modules/@trpc/react-query/node_modules/@tanstack/react-query/build/lib/useBaseQuery.mjs:12:23)
at useQuery (.../bug-trpc/node_modules/@trpc/react-query/node_modules/@tanstack/react-query/build/lib/useQuery.mjs:7:10)
at Object.useQuery$1 [as useQuery] (.../bug-trpc/node_modules/@trpc/react-query/dist/createHooksInternal-bdff7171.mjs:370:22)
                                      at .../bug-trpc/node_modules/@trpc/react-query/dist/createHooksInternal-bdff7171.mjs:76:30
  at Object.apply (.../bug-trpc/node_modules/@trpc/server/dist/index-f91d720c.mjs:67:20)
at IndexPage (webpack-internal:///./src/pages/index.tsx:14:71)
at renderWithHooks (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
at renderIndeterminateComponent (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
at renderElement (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
at renderNodeDestructiveImpl (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
at renderNodeDestructive (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
at renderIndeterminateComponent (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
at renderElement (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
at renderNodeDestructiveImpl (.../bug-trpc/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11) {
  page: '/'
```

### Link to reproduction

https://github.com/junya-ishibuchi/bug-report-trpc

### To reproduce

1.  `git clone https://github.com/junya-ishibuchi/bug-report-trpc.git`
2. `cd bug-report-trpc`
3. `bun install`
4. `bun dev`
5. Access the application to localhost:3000
6. You can see the error displayed

Here is the prompt for setting up Next.js.
```
✔ What is your project named? … bug-trpc
✔ Would you like to use TypeScript? … Yes
✔ Would you like to use ESLint? … Yes
✔ Would you like to use Tailwind CSS? … Yes
✔ Would you like to use `src/` directory? … Yes
✔ Would you like to use App Router? (recommended) … No
✔ Would you like to customize the default import alias (@/*)? … No
Creating a new Next.js app in .../bug-trpc.
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5014">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5014/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5014/pledge.svg">
</picture>
</a>

**Comment by spirobel** [comment]
I had the same error message before changing the tanstack / trpc version.
we should upgrade the nextjs setup docs in the same way.
https://github.com/trpc/trpc/issues/5006
