### ISSUE TITLE
bug: TRPC Calls from RSC cause Next to throw dynamic server error.

### ISSUE THREAD

**Issue by rydonahue1** [trpc/trpc#5305]
### Provide environment information

```
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 49.68 GB / 63.21 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.121)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @tanstack/react-query: ^4.36.1 => 4.36.1 
    @trpc/client: ^10.43.6 => 10.45.0 
    @trpc/next: ^10.43.6 => 10.45.0 
    @trpc/react-query: ^10.43.6 => 10.45.0 
    @trpc/server: ^10.43.6 => 10.45.0 
    next: ^14.0.4 => 14.0.4 
    react: 18.2.0 => 18.2.0 
    typescript: ^5.1.6 => 5.3.3 
```

### Describe the bug

Noticed this error get thrown when starting up a base T3 app and then running build right away

```
 Generating static pages (0/4)  [=   ]y [TRPCClientError]: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
    at y.from (C:\Code\planetscale-debug\.next\server\app\page.js:1:26283)
    at C:\Code\planetscale-debug\.next\server\app\page.js:5:1636 {
  meta: undefined,
  shape: undefined,
  data: undefined,
  [cause]: n [Error]: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
      at s (C:\Code\planetscale-debug\.next\server\chunks\362.js:1:4931)
      at d (C:\Code\planetscale-debug\.next\server\chunks\362.js:1:2674)
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:4476
      at C:\Code\planetscale-debug\node_modules\.pnpm\next@14.0.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:179176
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:5411
      at Object.subscribe (C:\Code\planetscale-debug\.next\server\app\page.js:1:25129)
      at Object.subscribe (C:\Code\planetscale-debug\.next\server\app\page.js:5:5185)
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:5313
      at Object.subscribe (C:\Code\planetscale-debug\.next\server\app\page.js:1:25129)
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:881 {
    digest: 'DYNAMIC_SERVER_USAGE'
  }
}
y [TRPCClientError]: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
    at y.from (C:\Code\planetscale-debug\.next\server\app\page.js:1:26283)
    at C:\Code\planetscale-debug\.next\server\app\page.js:5:1636 {
  meta: undefined,
  shape: undefined,
  data: undefined,
  [cause]: n [Error]: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
      at s (C:\Code\planetscale-debug\.next\server\chunks\362.js:1:4931)
      at d (C:\Code\planetscale-debug\.next\server\chunks\362.js:1:2674)
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:4476
      at C:\Code\planetscale-debug\node_modules\.pnpm\next@14.0.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:179176
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:5411
      at Object.subscribe (C:\Code\planetscale-debug\.next\server\app\page.js:1:25129)
      at Object.subscribe (C:\Code\planetscale-debug\.next\server\app\page.js:5:5185)
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:5313
      at Object.subscribe (C:\Code\planetscale-debug\.next\server\app\page.js:1:25129)
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:881 {
    digest: 'DYNAMIC_SERVER_USAGE'
  }
}
```

### Link to reproduction

https://github.com/t3-oss/create-t3-app

### To reproduce

Created t3 app with trpc, drizzle and pg or planetscale then run build command (also occurs with pnpm as well). 

### Additional information

The error is preventable by adding `export const dynamic = "force-dynamic"` or calling `cookies()` before the api call within the RSC.

Alternatively not passing the cookies to the TRPC Provider also appears to work, I am just not sure how this would effect T3 stack. 

Since neither of these were included with the stack, I am assuming something must have changed with a release of Next to cause the build errors. But if they are the correct approach, feel free to let me know. Thanks!

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5305">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5305/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5305/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Actually, this belongs in the create-t3-app, repo, you can copy/paste the above to https://github.com/t3-oss/create-t3-app/issues/new

Sorry for telling you to put it here.

**Comment by rydonahue1** [comment]
> Actually, this belongs in the create-t3-app, repo, you can copy/paste the above to https://github.com/t3-oss/create-t3-app/issues/new
> 
> Sorry for telling you to put it here.

No worries, thanks for checking it out!
