### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [trpc/trpc#5405]
### Provide environment information

```
  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 12.13 GB / 31.93 GB
  Binaries:
    Node: 20.10.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.3 - D:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.3 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    typescript: ^5.3.3 => 5.3.3
```

### Describe the bug

If I call the tRPC fetch api I get this error:
```
⨯ TypeError: Invalid URL
at new URL (node:internal/url:775:36)
at fetchRequestHandler (file:///F:/programming-projects/Weather-App/node_modules/.pnpm/@trpc+server@10.45.0/node_modules/@trpc/server/dist/adapters/fetch/index.mjs:24:17)
at handler (webpack-internal:///(api)/./src/pages/api/trpc/[trpc].ts:16:92)
at F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:21:3039
at F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\trace\tracer.js:133:36
at NoopContextManager.with (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:7062)
at ContextAPI.with (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:518)
at NoopTracer.startActiveSpan (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:18093)
at ProxyTracer.startActiveSpan (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:18854)
at F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\trace\tracer.js:122:103
at NoopContextManager.with (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:7062)
at ContextAPI.with (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:518)
at NextTracerImpl.trace (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\trace\tracer.js:122:28)
at K (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:21:2970)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
code: 'ERR_INVALID_URL',
input: '/api/trpc/weather.getWeather?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22coordinates%22%3A%7B%22lat%22%3A52.30141%2C%22lon%22%3A13.633%7D%2C%22timezone%22%3A%22Europe%2FBerlin%22%2C%22lang%22%3A%22en%22%7D%7D%7D',
page: '/api/trpc/[trpc]'
}
```

### Link to reproduction

https://codesandbox.io/p/sandbox/github/The-Creative-Programming-Group/Weather-App/tree/move-to-edge

### To reproduce

Fill out all the envs according to the env.example file
Start the dev server in the codesandbox and go to /home
look in the terminal and see the error

### Additional information

If there is enough information I could try to fix this bug.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
I haven't been able to look at your sandbox as I'm on my phone, but usually this style of error is just misconfiguration or that there's something server-side that messes with the request

**Comment by FleetAdmiralJakob** [comment]
I looked again at the code, and it seems all like in the example.

**Comment by KATT** [comment]
@FleetAdmiralJakob you have to create a reproduction that is easier to use, I don't have access to all of those services defined & I don't have the time to go through all of that to validate the bug.

**Comment by KATT** [comment]
You can try out the latest canary-tagged release once #5410 is merged to see if it works


Update your `package.json` to use the latest version of tRPC:

```diff
-    "@trpc/client": "^x.y.z",
-    "@trpc/next": "^x.y.z",
-    "@trpc/react-query": "^x.y.z",
-    "@trpc/server": "^x.y.z",
+    "@trpc/client": "canary",
+    "@trpc/next": "canary",
+    "@trpc/react-query": "canary",
+    "@trpc/server": "canary",
```

Then run `npm install` or similar. Reopen the issue if updating to the canary doesn't solve it.

**Comment by FleetAdmiralJakob** [comment]
Sorry for the problems with the reproduction of the issue. I will build a better reproduction right now if I'm at home.

Futhermore I will try the canary release and look if it solves my problem.

Thank you so much for your time in fixing this problem.

**Comment by FleetAdmiralJakob** [comment]
Update 1: After changing the trpc version to canary I no longer get the invalid URL error and instead the error:

<details>
<summary>New error</summary>

```
⨯ TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
     at Function.fromEntries (<anonymous>)
     at fetchRequestHandler (file:///F:/programming-projects/Weather-App/node_modules/.pnpm/@trpc+server@10.45.1-canary.23/node_modules/@trpc/server/dist/adapters/fetch/index.mjs:32:25)
     at handler (webpack-internal:///(api)/./src/pages/api/trpc/[trpc].ts:16:92)
     at F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:21:3039
     at F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\trace\tracer.js:133:36
     at NoopContextManager.with (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:7062)
     at ContextAPI.with (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:518)
     at NoopTracer.startActiveSpan (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:18093)
     at ProxyTracer.startActiveSpan (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:18854)
     at F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\trace\tracer.js:122:103
     at NoopContextManager.with (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:7062)
     at ContextAPI.with (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:518)
     at NextTracerImpl.trace (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\trace\tracer.js:122:28)
     at K (F:\programming-projects\Weather-App\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:21:2970)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
   page: '/api/trpc/[trpc]'
}
```

</details>

But since this is impossible for you to debug I will work on a smaller code sandbox for the reproduction

**Comment by FleetAdmiralJakob** [comment]
Here is a minimal repro of this issue: https://stackblitz.com/edit/stackblitz-starters-twslab?file=trpc-fetch-api-bug-repro%2Fsrc%2Fpages%2Fapi%2Ftrpc%2F%5Btrpc%5D.ts

**Comment by juliusmarminge** [comment]
So the problem is you're using the fetch adapter in next.js pages router which does not use WinterCG Request/Response.

You can either:

- [ ] use a route handler in the app directory
- [ ] make the API endpoint (`src/pages/api/trpc/[trpc].ts` use the edge runtime, which does use WinterCG Request/Response:
  ```diff
  +  export const config = { runtime: 'edge' };
  ```
- [ ] use the next.js adapter: https://trpc.io/docs/server/adapters/nextjs
