### ISSUE TITLE
docs: Standalone server example not working

### ISSUE THREAD

**Issue by kzuraniewski** [trpc/trpc#5882]
### Area of Improvement

The [standalone server](https://github.com/trpc/trpc/tree/next/examples/standalone-server) example appears to not run correctly. After opening it in StackBlitz, the following error occurs: 

```
[dev:server] TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/projects/kkviknopl.github/src/server.ts
[dev:server]     at NodeError (node:internal/errors:101:4149)
[dev:server]     at getFileProtocolModuleFormat (node:internal/modules/esm/get_format:149:1318)
[dev:server]     at defaultGetFormat (node:internal/modules/esm/get_format:149:1953)
[dev:server]     at defaultLoad (node:internal/modules/esm/load:153:1154)
[dev:server]     at internal/modules/esm/hooks/nextHookFactory/< (node:internal/modules/esm/hooks:151:8835)
[dev:server]     at load (node:internal/modules/esm/hooks:151:4461)
[dev:server]     at handleMessage (node:internal/modules/esm/worker:162:1705)
[dev:server]     at checkForMessages (node:internal/modules/esm/worker:162:1253)
[dev:server]     at processImmediate (node:internal/timers:246:5146)
[dev:server]     at _0x59e0f0/</< (https://kkviknoplgithub-kimp.w-corp-staticblitz.com/blitz.70dbe416.js:40:517936)
[dev:server]     at _0x4f97ff/_0x305956.handle< (https://kkviknoplgithub-kimp.w-corp-staticblitz.com/blitz.70dbe416.js:40:517801)
[dev:server]     at _0x47accc (https://kkviknoplgithub-kimp.w-corp-staticblitz.com/blitz.70dbe416.js:19:600258)
[dev:server]     at _0x1d49cf (https://kkviknoplgithub-kimp.w-corp-staticblitz.com/blitz.70dbe416.js:19:600463)
[dev:server]     at  (https://kkviknoplgithub-kimp.w-corp-staticblitz.com/blitz.70dbe416.js:19:599787) {
[dev:server]   code: 'ERR_UNKNOWN_FILE_EXTENSION'
[dev:server] }
[dev:server] 
[dev:server] Node.js 18.20.3
```

### Link to related docs

https://github.com/trpc/trpc/tree/next/examples/standalone-server

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

**Comment by viliusddd** [comment]
<details>
<summary>Seems to be working ok for me:</summary>

<img src=https://github.com/user-attachments/assets/cf7cd9b4-863f-48b4-8f33-769c5e8fbcf1></img>
</details>

Went to https://github.com/trpc/trpc/tree/next/examples/standalone-server, 
then https://stackblitz.com/github/trpc/trpc/tree/main/examples/standalone-server?file=src%2Fserver.ts,src%2Fclient.ts&view=editor&terminal=dev

**Comment by kzuraniewski** [comment]
I think this is a StackBlitz issue on Firefox then. Might be unrelated
