### ISSUE TITLE
bug: Error: `headers` was called outside a request scope.

### ISSUE THREAD

**Issue by ridhwaans** [trpc/trpc#6145]
### Provide environment information

System:
    OS: Linux 4.19 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 5.58 GB / 7.73 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 9.1.0 - ~/.local/share/pnpm/pnpm
    bun: 1.1.27 - ~/.bun/bin/bun
  npmPackages:
    typescript: ^5.4.5 => 5.6.3

more: 
"lucia": "^3.2.0",
"next": "14.2.3",
"@tanstack/react-query": "^5.39.0",
"@trpc/client": "next",
"@trpc/react-query": "next",
"@trpc/server": "next",
    
### Describe the bug

Using a nextjs app router webapp with a trpc server and trpc client  
`dashboard/page.tsx` is a server component which further renders other client components such as ContentCarousel
```javascript
//ContentCarousel.tsx
`use client`  
import { api } from '@/lib/trpc/react';
const ContentCarousel = ({
  options
}: CarouselProps) => {
const queryResult = api.home.queryMedia.useQuery(options);
```

When the dashboard page loads, it returns
```
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 3247530286
```
```
Error: `headers` was called outside a request scope. Read more: https://nextjs.org/docs/messages/next-dynamic-api-wrong-context
    at getExpectedRequestStore (/home/ridhwaans/Source/test/node_modules/next/dist/client/components/request-async-storage.external.js:28:11)
    at d (/home/ridhwaans/Source/test/apps/web/.next/server/chunks/4902.js:139:21531)
    at /home/ridhwaans/Source/test/apps/web/.next/server/chunks/4868.js:1:4786
    at /home/ridhwaans/Source/test/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:185072
    at /home/ridhwaans/Source/test/apps/web/.next/server/chunks/8419.js:4:1730
    at Object.apply (/home/ridhwaans/Source/test/apps/web/.next/server/chunks/8419.js:4:715)
    at ee (/home/ridhwaans/Source/test/apps/web/.next/server/app/dashboard/page.js:16:1399)
    at 67268 (/home/ridhwaans/Source/test/apps/web/.next/server/app/dashboard/page.js:16:4573)
    at t (/home/ridhwaans/Source/test/apps/web/.next/server/webpack-runtime.js:1:128)
    at 47197 (/home/ridhwaans/Source/test/apps/web/.next/server/app/dashboard/page.js:1:1721) {
  digest: '212130697'
}
```
The only reference to headers I found are in the trpcContext, trpc client and trpc dynamic route `/trpc/[trpc]/route.ts` .  

Not sure it is because a client component is calling server component or if it is lucia auth.   
There is so much code it is hard to debug  

### Link to reproduction

https://stackblitz.com/github/trpc/examples-next-minimal-starter?file=README.md

### To reproduce

1. Use the code for trpcContext
```javascript
//api/src/trpc.ts
import { initTRPC, TRPCError } from '@trpc/server';
import superjson from 'superjson';
import { ZodError } from 'zod';

import { auth } from '@project/auth';
import { db } from '@project/db';

export const createTRPCContext = async (opts: { headers: Headers }) => {
  const { session, user } = await auth();

  return {
    db,
    session,
    user,
    ...opts,
  };
};

const t = initTRPC.context<typeof createTRPCContext>().create({
  transformer: superjson,
  errorFormatter({ shape, error }) {
    return {
      ...shape,
      data: {
        ...shape.data,
        zodError:
          error.cause instanceof ZodError ? error.cause.flatten() : null,
      },
    };
  },
});
export const createCallerFactory = t.createCallerFactory;

export const createRouter = t.router;

export const publicProcedure = t.procedure;

export const protectedProcedure = t.procedure.use(({ ctx, next }) => {
  if (!ctx.session || !ctx.user) {
    throw new TRPCError({ code: 'UNAUTHORIZED' });
  }

  return next({
    ctx: {
      session: { ...ctx.session },
      user: { ...ctx.user },
    },
  });
});

```

```javascript
//app/web/src/lib/trpc/react.tsx
'use client';

import { useState } from 'react';

import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { loggerLink, unstable_httpBatchStreamLink } from '@trpc/client';
import { createTRPCReact } from '@trpc/react-query';
import { type inferRouterInputs, type inferRouterOutputs } from '@trpc/server';
import superjson from 'superjson';

import { type AppRouter } from '@project/api';
import { getBaseUrl } from '@project/utils/url';

const createQueryClient = () => new QueryClient();

let clientQueryClientSingleton: QueryClient | undefined = undefined;
const getQueryClient = () => {
  if (typeof window === 'undefined') {
    return createQueryClient();
  }
  return (clientQueryClientSingleton ??= createQueryClient());
};

export const api = createTRPCReact<AppRouter>();

export type RouterInputs = inferRouterInputs<AppRouter>;
export type RouterOutputs = inferRouterOutputs<AppRouter>;

/**
 * This component is used to initialize the trpc & react-query pairing on the client side.
 * @param props The props to the component.
 * @param props.children The children to render.
 * @returns react-query and trpc providers wrapper around the children.
 */
export function TRPCReactProvider(props: { children: React.ReactNode }) {
  const queryClient = getQueryClient();

  const [trpcClient] = useState(() =>
    api.createClient({
      links: [
        loggerLink({
          enabled: (op) =>
            process.env.NODE_ENV === 'development' ||
            (op.direction === 'down' && op.result instanceof Error),
        }),
        unstable_httpBatchStreamLink({
          transformer: superjson,
          url: getBaseUrl() + '/api/trpc',
          headers: () => {
            const headers = new Headers();
            headers.set('x-trpc-source', 'nextjs-react');
            return headers;
          },
        }),
      ],
    }),
  );

  return (
    <QueryClientProvider client={queryClient}>
      <api.Provider client={trpcClient} queryClient={queryClient}>
        {props.children}
      </api.Provider>
    </QueryClientProvider>
  );
}

```

```javascript
//app/web/src/lib/trpc/server.ts
import 'server-only';

import { cache } from 'react';
import { headers } from 'next/headers';

import { createCaller, createTRPCContext } from '@project/api';

const createContext = cache(async () => {
  const heads = new Headers(headers());
  heads.set('x-trpc-source', 'rsc');

  return createTRPCContext({
    headers: heads,
  });
});

export const api = createCaller(createContext);

```

```javascript
//app/web/src/app/api/trpc/[trpc]/route.ts
import { type NextRequest } from 'next/server';

import { fetchRequestHandler } from '@trpc/server/adapters/fetch';

import { appRouter, createTRPCContext } from '@project/api';
import { env } from '@project/env/web';

const createContext = async (req: NextRequest) => {
  return createTRPCContext({
    headers: req.headers,
  });
};

const handler = (req: NextRequest) =>
  fetchRequestHandler({
    endpoint: '/api/trpc',
    req,
    router: appRouter,
    createContext: () => createContext(req),
    onError: ({ path, error }) => {
      if (env.NODE_ENV === 'development') {
        console.error(
          `❌ tRPC failed on ${path ?? '<no-path>'}: ${error.message}`,
        );
      }
    },
  });

export { handler as GET, handler as POST };

```
2. Use the client component and call useQuery
3. Load the page and it crashes

### Additional information

related
https://github.com/trpc/trpc/discussions/5704

_No response_

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6145">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6145/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6145/pledge.svg">
</picture>
</a>

**Comment by ridhwaans** [comment]
The client components making the trpc client request dont have access to the request lifecycle, which is only available in server components or getServerSideProps. 
I think i have to rewrite the client component to use the fetch request handler as defined above. That one doesnt work in development mode but calling a trpc router method does

**Comment by juliusmarminge** [comment]
Please create the reproduction and link the completed sandbox/repo. Even if you have provided the content of a bunch of files here it's tedious for us to setup and then it might still not match your setup.

**Comment by ridhwaans** [comment]
I think I found  I found why it is failing
with `next build --debug`

> Static generation failed due to dynamic usage on /catalogue, reason: headers

Static site generation on dynamic routes, that is what is recommended on the nextjs docs

There is external data involved, I think I may need to do getStaticPaths or getStaticPath and reuse my trpc client

Also use getServerSideProps for the dynamic pages that give a cookies reason
