### ISSUE TITLE
bug: TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by ian** [trpc/trpc#6289]
### Provide environment information

  System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 393.28 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
    pnpm: 9.7.0 - ~/.nvm/versions/node/v18.20.4/bin/pnpm
    bun: 1.1.27 - ~/.nvm/versions/node/v18.20.4/bin/bun
  Browsers:
    Brave Browser: 131.1.73.91
    Chrome: 131.0.6778.87
    Safari: 17.6

### Describe the bug

After upgrading to Expo 52, tRPC no longer seems to function. Getting a very deep error which stack trace doesn't effectively tell where the error is happening.

Trace:
```
TypeError: Cannot read property 'then' of undefined
    at anonymous (http://192.168.0.64:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=src%2Fapp&unstable_transformProfile=hermes-stable:263307:23)
    at tryCallTwo (address at InternalBytecode.js:1:1222)
    at doResolve (address at InternalBytecode.js:1:2541)
    at Promise (address at InternalBytecode.js:1:1318)
    at requestAsPromise (http://192.168.0.64:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=src%2Fapp&unstable_transformProfile=hermes-stable:263305:43)
    at query (http://192.168.0.64:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=src%2Fapp&unstable_transformProfile=hermes-stable:263318:37)
    at apply (native)
    at ?anon_0_ (http://192.168.0.64:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=src%2Fapp&unstable_transformProfile=hermes-stable:276727:44)
    at next (native)
    at asyncGeneratorStep (http://192.168.0.64:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=src%2Fapp&unstable_transformProfile=hermes-stable:5554:19)
    at _next (http://192.168.0.64:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=src%2Fapp&unstable_transformProfile=hermes-stable:5568:29)
    at anonymous (http://192.168.0.64:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=src%2Fapp&unstable_transformProfile=hermes-stable:5573:14)
    at tryCallTwo (address at InternalBytecode.js:1:1222)
    at doResolve (address at InternalBytecode.js:1:2541)
    at Promise (address at InternalBytecode.js:1:1318)
    at anonymous (http://192.168.0.64:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=src%2Fapp&unstable_transformProfile=hermes-stable:5565:25)
    at apply (native)
    at anonymous (http://192.168.0.64:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=src%2Fapp&unstable_transformProfile=hermes-stable:276734:30)
    at fetchFn (http://192.168.0.64:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=src%2Fapp&unstable_transformProfile=hermes-stable:267836:25)
    at run (http://192.168.0.64:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=src%2Fapp&unstable_transformProfile=hermes-stable:266531:53)
    at anonymous (http://192.168.0.64:8081/node_modules/expo-router/entry.bundle//&platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=1&transform.routerRoot=src%2Fapp&unstable_transformProfile=hermes-stable:266556:16)
    at tryCallOne (address at InternalBytecode.js:1:1180)
    at anonymous (address at InternalBytecode.js:1:1874)
```

### Link to reproduction

https://github.com/ian/trpc-expo-error-repro

### To reproduce

See TrpcProvider below, this error happens when running any query:

`const { data, isLoading, error } = trpc.items.list.useQuery(...)`

Results in logs:

```
 (NOBRIDGE) LOG  {"data": undefined, "error": null, "isLoading": true}
 (NOBRIDGE) LOG  {"data": undefined, "error": [TypeError: Cannot read property 'then' of undefined], "isLoading": false}
```

Versions:

"@tanstack/query-async-storage-persister": 5.62.2
  "@tanstack/react-query": 5.62.2
  "@tanstack/react-query-persist-client": 5.62.2
  "@trpc/client": 11.0.0-rc.648
  "@trpc/next": 11.0.0-rc.648
  "@trpc/react-query": 11.0.0-rc.648
  "@trpc/server": 11.0.0-rc.648

### Additional information

TrpcProvider:

```
import React, { useMemo } from "react"
import { SuperJSON } from "superjson"
import { QueryClient } from "@tanstack/react-query"
import {
  PersistQueryClientProvider,
} from "@tanstack/react-query-persist-client"
import { createAsyncStoragePersister } from "@tanstack/query-async-storage-persister"
import { httpLink } from "@trpc/client"
import AsyncStorage from "@react-native-async-storage/async-storage"

import { trpc } from "@/lib/trpc"
import { Config } from "@/lib/config"

export const persister = createAsyncStoragePersister({
  storage: AsyncStorage,
  throttleTime: 3000,
})

export function TRPCProvider(props: { children: React.ReactNode }) {
  const queryClient = useMemo(() => new QueryClient(), [])
  const trpcClient = useMemo(() => {
    const links = [
      httpLink({
        url: `${Config.HOST_URL}/trpc`,
      }),
    ]

    return trpc.createClient({
      transformer: SuperJSON,
      links,
    })
  }, [])

  return (
    <trpc.Provider client={trpcClient} queryClient={queryClient}>
      <PersistQueryClientProvider
        onSuccess={() =>
          queryClient
            .resumePausedMutations()
            .then(() => queryClient.invalidateQueries())
        }
        persistOptions={{ persister }}
        client={queryClient}
      >
        {props.children}
      </PersistQueryClientProvider>
    </trpc.Provider>
  )
}
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/6289">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/6289/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/6289/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Sounds unrelated to trpc 

cc @juliusmarminge t3 turbo works right?

**Comment by ian** [comment]
@KATT t3 still seems to be on expo 51: https://github.com/t3-oss/create-t3-turbo/blob/main/apps/expo/package.json#L25C4-L25C24

**Comment by ian** [comment]
I will work on a public repo, it's a large monorepo that will need to be extracted.

**Comment by ian** [comment]
@KATT here's a monorepo api + expo52 version that shows off the error: https://github.com/ian/trpc-expo-error-repro

![CleanShot 2024-12-04 at 07 57 33@2x](https://github.com/user-attachments/assets/4aa49890-4e35-4507-b250-5770a8b50d98)

**Comment by julius-ping-test** [comment]
> @KATT @juliusmarminge t3 still seems to be on expo 51: https://github.com/t3-oss/create-t3-turbo/blob/main/apps/expo/package.json#L25C4-L25C24

We have a pending PR to upgrade and that worked last time i tried it: https://github.com/t3-oss/create-t3-turbo/pull/1248

**Comment by juliusmarminge** [comment]
> @KATT @juliusmarminge t3 still seems to be on expo 51: https://github.com/t3-oss/create-t3-turbo/blob/main/apps/expo/package.json#L25C4-L25C24

We have a pending PR to upgrade and that worked last time i tried it: https://github.com/t3-oss/create-t3-turbo/pull/1248

**Comment by ian** [comment]
Thanks for the example @juliusmarminge, figured out it's `@tanstack/react-query-persist-client` that's causing the problem.
